// Code generated by bindings/codegen/golang.py from bindings/options.schema.json. DO NOT EDIT.
//
// Change `inkvec::Options` in crates/inkvec, regenerate the schema (cargo test -p inkvec),
// then run `python bindings/codegen/generate.py`.

package inkvec

// Options for one trace. Every field is optional: nil takes the default. Names and meanings
// are the Rust library's (`inkvec::Options`); the options travel to it as one JSON object,
// which it checks in full, so an unknown name or a value out of range is an
// ErrInvalidOptions rather than a silent no-op. Set a field with [Ptr]:
//
//	opts := &inkvec.Options{Colors: inkvec.Ptr(16), NoBackground: inkvec.Ptr(true)}
//
// An option newer than this struct can be passed with [TraceJSON].
type Options struct {
	// Sets the description-length cost of a coordinate, in pixels: lambda = ln(extent /
	// precision). Smaller values buy more detail with more coordinates. It does not set the
	// digits written; coordinates are always written at 2 decimals.
	//
	// A number > 0. Default: 0.1.
	Precision *float64 `json:"precision,omitempty"`

	// Discard features smaller than this area, in square pixels.
	//
	// A number > 0. Default: 2.0.
	MinArea *float64 `json:"min_area,omitempty"`

	// Maximum palette size.
	//
	// An integer >= 1 and <= 4096. Default: 64.
	Colors *int `json:"colors,omitempty"`

	// OKLab distance below which two colours are treated as one ink.
	//
	// A number >= 0. Default: 0.035.
	Merge *float64 `json:"merge,omitempty"`

	// Inputs larger than this on their longer side, in pixels, are traced at this size and the
	// SVG is written at the original size. Trace time grows with the pixel count. 0 means no
	// cap.
	//
	// An integer. Default: 2048.
	MaxDim *int `json:"max_dim,omitempty"`

	// Advisory wall-clock budget, in seconds; 0 means none. Gradient-band merging stops at 60%
	// of it and the boundary solve gets 25%; the output is still a correct trace, with more
	// fills or a less polished outline. A nonzero budget makes the output depend on machine
	// speed and load, so it is no longer reproducible.
	//
	// A number >= 0. Default: 0.0.
	TimeBudget *float64 `json:"time_budget,omitempty"`

	// Transparent margin around the output, as a fraction of the larger side. The viewBox
	// grows; the geometry does not move.
	//
	// A number >= 0. Default: 0.0.
	Margin *float64 `json:"margin,omitempty"`

	// Knock the background out: the face that covers the whole canvas is not painted, so the
	// artwork sits on transparency.
	//
	// Default: false.
	NoBackground *bool `json:"no_background,omitempty"`

	// No ids or groups, no trailing zeros. Same geometry, typically about a tenth smaller.
	//
	// Default: false.
	Minify *bool `json:"minify,omitempty"`

	// Trace transparency natively: each ink is a colour and an opacity, and the transparent
	// ground is an ink of its own, instead of the image being composited onto a matte first.
	// Holes stay holes, white artwork on a transparent ground traces, glows and shadows stay
	// translucent, and a fade is one gradient of colour and opacity. An opaque input traces
	// the same either way. On by default, as on the command line (where the environment
	// variable INKVEC_NATIVE_ALPHA=0 turns the default off); false composites onto a matte
	// first, as releases up to 0.1.3 did.
	//
	// Default: true.
	NativeAlpha *bool `json:"native_alpha,omitempty"`

	// With native_alpha off, carry the input's transparency into the SVG: a face the source
	// drew transparent becomes a hole, one drawn at a single opacity keeps it as fill-opacity,
	// and white artwork on a transparent ground survives. Changes nothing for an opaque input,
	// and nothing with native_alpha on (the default), which already carries the transparency
	// out.
	//
	// Default: false.
	Cutout *bool `json:"cutout,omitempty"`

	// Scale the fit tolerances with the raster, so a large, simple drawing gets the parameter
	// count of a small one. Trades fidelity for parsimony: small squares can come back as
	// circles and thin rings broken.
	//
	// Default: false.
	ContentUnits *bool `json:"content_units,omitempty"`

	// Shape harmonization (on by default): marks that repeat across the drawing are redrawn
	// from one consensus geometry per cluster, which saves parameters. A mark takes the
	// consensus only where that stays within 0.1 px of the boundary traced for it and costs
	// fewer parameters; a face another face is drawn against, and a fitted circle or rounded
	// rectangle, is never moved. Set it to false to skip the pass.
	//
	// Default: true.
	Harmonize *bool `json:"harmonize,omitempty"`

	// Shape-equivalence threshold for harmonization: the outline similarity (IoU after affine
	// normalisation) above which two marks count as the same shape.
	//
	// A number >= 0 and <= 1. Default: 0.92.
	HarmonizeThreshold *float64 `json:"harmonize_threshold,omitempty"`
}
