#!/usr/bin/env node
// Build @logolabs/inkvec from source.
//
//   node build.mjs              both WebAssembly builds, generated sources, TypeScript
//   node build.mjs --skip-wasm  generated sources and TypeScript only (wasm/ must exist)
//   node build.mjs --check      build nothing; fail if anything generated is stale
//
// Everything that describes the tracer comes from Rust, so the package follows the Rust
// code without edits here:
//
//   - the version is `[workspace.package] version` in the workspace Cargo.toml, written into
//     package.json and src/version.generated.ts;
//   - the option types and the README's options table are generated from
//     bindings/options.schema.json (itself generated from `inkvec::Options`) by
//     bindings/codegen/generate.py, with every other binding's;
//   - both WebAssembly builds come from tools/build_wasm.sh, the script that builds the
//     Space's, so the two cannot drift apart on the threaded build's flags.
//
// Prerequisites: a Rust toolchain with wasm32-unknown-unknown, nightly with rust-src (the
// threaded build), wasm-pack, bash, Python 3 (the code generators) and `npm install` in
// this folder (TypeScript).

import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { delimiter, dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const PKG = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(PKG, "../..");
const args = new Set(process.argv.slice(2));
for (const a of args) {
  if (!["--skip-wasm", "--check"].includes(a)) fail(`unknown argument ${a}`);
}
const CHECK = args.has("--check");

function fail(msg) {
  console.error(`build.mjs: ${msg}`);
  process.exit(1);
}

function run(cmd, argv, opts = {}) {
  console.log(`> ${[cmd, ...argv].join(" ")}`);
  const r = spawnSync(cmd, argv, { stdio: "inherit", ...opts });
  if (r.error) fail(`${cmd}: ${r.error.message}`);
  if (r.status !== 0) fail(`${cmd} exited with ${r.status}`);
}

/** Write `text` to `file`, or under --check report whether it already holds it. */
let stale = 0;
function emit(file, text) {
  const current = existsSync(file) ? readFileSync(file, "utf8").replace(/\r\n/g, "\n") : null;
  if (current === text) return;
  if (CHECK) {
    console.error(`stale: ${relative(ROOT, file)}`);
    stale++;
    return;
  }
  writeFileSync(file, text);
  console.log(`wrote ${relative(ROOT, file)}`);
}

// ---- version, from the workspace -------------------------------------------------------

function cargoVersion() {
  const toml = readFileSync(join(ROOT, "Cargo.toml"), "utf8");
  const section = /^\[workspace\.package\]\s*$([\s\S]*?)(?=^\[)/m.exec(toml);
  const v = section && /^version\s*=\s*"([^"]+)"/m.exec(section[1]);
  if (!v) fail("no [workspace.package] version in Cargo.toml");
  return v[1];
}

const VERSION = cargoVersion();
{
  const file = join(PKG, "package.json");
  const pkg = JSON.parse(readFileSync(file, "utf8"));
  pkg.version = VERSION;
  emit(file, JSON.stringify(pkg, null, 2) + "\n");

  const lockFile = join(PKG, "package-lock.json");
  const lock = JSON.parse(readFileSync(lockFile, "utf8"));
  lock.version = VERSION;
  lock.packages[""].version = VERSION;
  emit(lockFile, JSON.stringify(lock, null, 2) + "\n");
}
emit(
  join(PKG, "src/version.generated.ts"),
  "// GENERATED by packages/npm/build.mjs from the workspace Cargo.toml. Do not edit.\n" +
    `export const VERSION = ${JSON.stringify(VERSION)};\n`,
);

// ---- option types and tables, from the Rust schema ------------------------------------
//
// bindings/codegen/generate.py renders every language's artifacts from the schema:
// src/options.generated.ts (typescript.py) and this README's options table
// (docs_tables.py) among them. --check only verifies, as the other bindings' CI does.

function python() {
  const candidates = process.env.INKVEC_PYTHON
    ? [[process.env.INKVEC_PYTHON]]
    : [["python3"], ["python"], ["py", "-3"]];
  for (const [cmd, ...pre] of candidates) {
    const r = spawnSync(cmd, [...pre, "--version"], { encoding: "utf8" });
    if (r.status === 0) return [cmd, pre];
  }
  fail("no Python 3 found for bindings/codegen (set INKVEC_PYTHON)");
}
{
  const [py, pre] = python();
  const gen = join(ROOT, "bindings", "codegen", "generate.py");
  const r = spawnSync(py, [...pre, gen, ...(CHECK ? ["--check"] : [])], { encoding: "utf8" });
  process.stdout.write(r.stdout ?? "");
  process.stderr.write(r.stderr ?? "");
  if (r.status !== 0) {
    if (CHECK) stale++;
    else fail("bindings/codegen/generate.py failed");
  }
}

// ---- licence files -----------------------------------------------------------------------

for (const f of ["LICENSE", "NOTICE"]) {
  emit(join(PKG, f), readFileSync(join(ROOT, f), "utf8").replace(/\r\n/g, "\n"));
}

// ---- WebAssembly -------------------------------------------------------------------------

const WASM = join(PKG, "wasm");

function bash() {
  if (process.env.INKVEC_BASH) return process.env.INKVEC_BASH;
  // On Windows a bare `bash` can be WSL's, which cannot see this toolchain. Prefer Git's.
  if (process.platform === "win32") {
    for (const p of [
      join(process.env.ProgramFiles ?? "C:\\Program Files", "Git", "bin", "bash.exe"),
      join(process.env["ProgramFiles(x86)"] ?? "C:\\Program Files (x86)", "Git", "bin", "bash.exe"),
    ]) {
      if (existsSync(p)) return p;
    }
  }
  return "bash";
}

/**
 * The rayon worker helper imports its parent bindings when a worker starts, and registers a
 * listener on `self` when it is first imported. Node.js has no `self` on its main thread,
 * so that one statement is guarded; a browser, which has one, runs it exactly as before.
 * `tools/build_wasm.sh` has already pointed its import at `inkvec_wasm.js`.
 */
function patchWorkerHelper() {
  const snippets = join(WASM, "threads", "snippets");
  const helpers = readdirSync(snippets).map((d) => join(snippets, d, "src", "workerHelpers.js"));
  if (helpers.length !== 1 || !existsSync(helpers[0])) fail("expected one rayon workerHelpers.js");
  const file = helpers[0];
  const from = "waitForMsgType(self, 'wasm_bindgen_worker_init').then(";
  const to =
    "(typeof self !== 'undefined' && typeof self.addEventListener === 'function'\n" +
    "  ? waitForMsgType(self, 'wasm_bindgen_worker_init')\n" +
    "  : new Promise(() => {})).then(";
  let text = readFileSync(file, "utf8");
  if (!text.includes(to)) {
    if (!text.includes(from)) fail(`rayon helper changed shape; cannot guard ${from}`);
    text = text.replace(from, to);
    writeFileSync(file, text);
  }
  if (!text.includes("import('../../../inkvec_wasm.js')")) {
    fail("rayon helper does not import ../../../inkvec_wasm.js; see tools/build_wasm.sh");
  }
}

if (!CHECK && !args.has("--skip-wasm")) {
  rmSync(WASM, { recursive: true, force: true });
  const env = {
    ...process.env,
    PATH: [join(homedir(), ".cargo", "bin"), process.env.PATH].join(delimiter),
    INKVEC_WASM_OUT_ST: join(WASM, "st"),
    INKVEC_WASM_OUT_MT: join(WASM, "threads"),
    INKVEC_WASM_TOKEN: "",
  };
  run(bash(), [join(ROOT, "tools", "build_wasm.sh")], { env, cwd: ROOT });
  for (const arm of ["st", "threads"]) {
    // wasm-pack's own manifest and readme would shadow this package's for tools that
    // look for the nearest package.json.
    for (const f of ["package.json", "README.md", ".gitignore", "LICENSE"]) {
      rmSync(join(WASM, arm, f), { force: true });
    }
  }
}
if (!CHECK) patchWorkerHelper();

for (const f of [
  "st/inkvec_wasm.js",
  "st/inkvec_wasm.d.ts",
  "st/inkvec_wasm_bg.wasm",
  "threads/inkvec_wasm.js",
  "threads/inkvec_wasm.d.ts",
  "threads/inkvec_wasm_bg.wasm",
]) {
  if (!existsSync(join(WASM, f))) fail(`wasm/${f} is missing; run node build.mjs`);
}
if (CHECK) patchCheck();

function patchCheck() {
  const snippets = join(WASM, "threads", "snippets");
  const [dir] = readdirSync(snippets);
  const text = readFileSync(join(snippets, dir, "src", "workerHelpers.js"), "utf8");
  if (!text.includes("typeof self !== 'undefined'")) fail("rayon helper is not patched; run node build.mjs");
}

// ---- TypeScript --------------------------------------------------------------------------

if (CHECK) {
  if (stale) fail(`${stale} generated file(s) are stale; run node build.mjs --skip-wasm`);
  if (!existsSync(join(PKG, "dist/index.js"))) fail("dist/ is missing; run node build.mjs");
  console.log(`@logolabs/inkvec ${VERSION}: generated files current`);
} else {
  const tsc = join(PKG, "node_modules", "typescript", "bin", "tsc");
  if (!existsSync(tsc)) fail("TypeScript is not installed; run npm install in packages/npm");
  rmSync(join(PKG, "dist"), { recursive: true, force: true });
  run(process.execPath, [tsc, "-p", join(PKG, "tsconfig.json")], { cwd: PKG });
  console.log(`@logolabs/inkvec ${VERSION} built`);
}
