# GENERATED by bindings/codegen/python_stub.py from bindings/options.schema.json.
# Do not edit: run `python bindings/codegen/generate.py` instead.
"""Inkvec: raster logos, icons and illustrations to compact, accurate SVG."""

from __future__ import annotations

import os
from typing import IO, Any, Dict, Optional, Union

__version__: str

#: Encoded image bytes, a path to an image file, a binary file object, a Pillow image, or
#: a uint8 numpy array of shape (H, W), (H, W, 3) or (H, W, 4).
ImageInput = Union[bytes, bytearray, memoryview, str, "os.PathLike[str]", IO[bytes], Any]

class InkvecError(Exception):
    """Base class of every error Inkvec raises."""

class InvalidImageError(InkvecError):
    """The input is not a decodable image, or raw pixels do not match the size given."""

class InvalidOptionsError(InkvecError):
    """An option is unknown, of the wrong type, or out of range."""

class InternalError(InkvecError):
    """The tracer failed. Not the caller's fault; worth a bug report."""

class Traced:
    """A finished trace. ``str(traced)`` is the SVG document."""

    @property
    def svg(self) -> str:
        """The SVG document."""
    @property
    def width(self) -> int:
        """Width of the input image, in pixels."""
    @property
    def height(self) -> int:
        """Height of the input image, in pixels."""
    def _repr_svg_(self) -> str: ...

def options_schema() -> Dict[str, Any]:
    """The JSON Schema of the options: every name, type, default, description and range."""

def defaults() -> Dict[str, Any]:
    """Every option at its default."""

def build_target() -> str:
    """The target the native library was compiled for, e.g. ``"x86_64-linux-gnu"``.

    Output is byte-identical between builds with the same target; another target can write
    the same drawing slightly differently (subpaths in another order, a last digit).
    """

def trace(
    image: ImageInput,
    *,
    precision: float = 0.1,
    min_area: float = 2.0,
    colors: int = 64,
    merge: float = 0.035,
    max_dim: int = 2048,
    time_budget: float = 0.0,
    margin: float = 0.0,
    no_background: bool = False,
    minify: bool = False,
    editability: bool = False,
    native_alpha: bool = True,
    cutout: bool = False,
    content_units: bool = False,
    harmonize: bool = True,
    harmonize_threshold: float = 0.92,
) -> Traced:
    """Trace an image to SVG.

    Args:
        image: Encoded image bytes (PNG, JPEG, WebP, GIF, BMP or TIFF), a path to such a
            file, a binary file object, a Pillow image, or a uint8 numpy array of shape
            (H, W), (H, W, 3) or (H, W, 4).
        precision:
            Sets the description-length cost of a coordinate, in pixels: lambda =
            ln(extent / precision). Smaller values buy more detail with more
            coordinates. It does not set the digits written; coordinates are always
            written at 2 decimals. Must be > 0.
        min_area:
            Discard features smaller than this area, in square pixels. Must be > 0.
        colors:
            Maximum palette size. Must be >= 1 and <= 4096.
        merge:
            OKLab distance below which two colours are treated as one ink. Must be >= 0.
        max_dim:
            Inputs larger than this on their longer side, in pixels, are traced at this
            size and the SVG is written at the original size. Trace time grows with the
            pixel count. 0 means no cap.
        time_budget:
            Advisory wall-clock budget, in seconds; 0 means none. Gradient-band merging
            stops at 60% of it and the boundary solve gets 25%; the output is still a
            correct trace, with more fills or a less polished outline. A nonzero budget
            makes the output depend on machine speed and load, so it is no longer
            reproducible. Must be >= 0.
        margin:
            Transparent margin around the output, as a fraction of the larger side. The
            viewBox grows; the geometry does not move. Must be >= 0.
        no_background:
            Knock the background out: the face that covers the whole canvas is not
            painted, so the artwork sits on transparency.
        minify:
            No ids or groups, no trailing zeros. Same geometry, typically about a tenth
            smaller.
        editability:
            Spend parameters on structure an artist can edit: joins between curves made
            G1-smooth, handles snapped to the axes and to 45 degrees, handles of one
            curve made equal in length, nodes that nearly share a coordinate made to
            share it, and rings that are their own mirror image locked into exact
            mirrors. Every change is guarded to the fit's own tolerance -- 3 sigma of
            the source point plus half a pixel, or 1.5 px for a mirror lock -- so the
            picture stays within a fraction of a pixel of the default trace; the price
            measured on 25 icons is about 0.04 dE00. Off by default.
        native_alpha:
            Trace transparency natively: each ink is a colour and an opacity, and the
            transparent ground is an ink of its own, instead of the image being
            composited onto a matte first. Holes stay holes, white artwork on a
            transparent ground traces, glows and shadows stay translucent, and a fade is
            one gradient of colour and opacity. An opaque input traces the same either
            way. On by default, as on the command line (where the environment variable
            INKVEC_NATIVE_ALPHA=0 turns the default off); false composites onto a matte
            first, as releases up to 0.1.3 did.
        cutout:
            With native_alpha off, carry the input's transparency into the SVG: a face
            the source drew transparent becomes a hole, one drawn at a single opacity
            keeps it as fill-opacity, and white artwork on a transparent ground
            survives. Changes nothing for an opaque input, and nothing with native_alpha
            on (the default), which already carries the transparency out.
        content_units:
            Scale the fit tolerances with the raster, so a large, simple drawing gets
            the parameter count of a small one. Trades fidelity for parsimony: small
            squares can come back as circles and thin rings broken.
        harmonize:
            Shape harmonization (on by default): marks that repeat across the drawing
            are redrawn from one consensus geometry per cluster, which saves parameters.
            A mark takes the consensus only where that stays within 0.1 px of the
            boundary traced for it and costs fewer parameters; a face another face is
            drawn against, and a fitted circle or rounded rectangle, is never moved. Set
            it to false to skip the pass.
        harmonize_threshold:
            Shape-equivalence threshold for harmonization: the outline similarity (IoU
            after affine normalisation) above which two marks count as the same shape.
            Must be >= 0 and <= 1.

    Raises:
        InvalidImageError: the input cannot be decoded.
        InvalidOptionsError: an option is unknown, of the wrong type, or out of range.
        InternalError: the tracer failed.
    """

def trace_rgba(
    pixels: Any,
    width: Optional[int] = None,
    height: Optional[int] = None,
    *,
    precision: float = 0.1,
    min_area: float = 2.0,
    colors: int = 64,
    merge: float = 0.035,
    max_dim: int = 2048,
    time_budget: float = 0.0,
    margin: float = 0.0,
    no_background: bool = False,
    minify: bool = False,
    editability: bool = False,
    native_alpha: bool = True,
    cutout: bool = False,
    content_units: bool = False,
    harmonize: bool = True,
    harmonize_threshold: float = 0.92,
) -> Traced:
    """Trace raw straight-RGBA8 pixels (row-major, tightly packed) to SVG.

    Args:
        pixels: A bytes-like buffer of exactly width * height * 4 bytes, or a Pillow image
            or uint8 numpy array (then width and height are read from it).
        width: Width in pixels; required for a flat buffer.
        height: Height in pixels; required for a flat buffer.
        precision:
            Sets the description-length cost of a coordinate, in pixels: lambda =
            ln(extent / precision). Smaller values buy more detail with more
            coordinates. It does not set the digits written; coordinates are always
            written at 2 decimals. Must be > 0.
        min_area:
            Discard features smaller than this area, in square pixels. Must be > 0.
        colors:
            Maximum palette size. Must be >= 1 and <= 4096.
        merge:
            OKLab distance below which two colours are treated as one ink. Must be >= 0.
        max_dim:
            Inputs larger than this on their longer side, in pixels, are traced at this
            size and the SVG is written at the original size. Trace time grows with the
            pixel count. 0 means no cap.
        time_budget:
            Advisory wall-clock budget, in seconds; 0 means none. Gradient-band merging
            stops at 60% of it and the boundary solve gets 25%; the output is still a
            correct trace, with more fills or a less polished outline. A nonzero budget
            makes the output depend on machine speed and load, so it is no longer
            reproducible. Must be >= 0.
        margin:
            Transparent margin around the output, as a fraction of the larger side. The
            viewBox grows; the geometry does not move. Must be >= 0.
        no_background:
            Knock the background out: the face that covers the whole canvas is not
            painted, so the artwork sits on transparency.
        minify:
            No ids or groups, no trailing zeros. Same geometry, typically about a tenth
            smaller.
        editability:
            Spend parameters on structure an artist can edit: joins between curves made
            G1-smooth, handles snapped to the axes and to 45 degrees, handles of one
            curve made equal in length, nodes that nearly share a coordinate made to
            share it, and rings that are their own mirror image locked into exact
            mirrors. Every change is guarded to the fit's own tolerance -- 3 sigma of
            the source point plus half a pixel, or 1.5 px for a mirror lock -- so the
            picture stays within a fraction of a pixel of the default trace; the price
            measured on 25 icons is about 0.04 dE00. Off by default.
        native_alpha:
            Trace transparency natively: each ink is a colour and an opacity, and the
            transparent ground is an ink of its own, instead of the image being
            composited onto a matte first. Holes stay holes, white artwork on a
            transparent ground traces, glows and shadows stay translucent, and a fade is
            one gradient of colour and opacity. An opaque input traces the same either
            way. On by default, as on the command line (where the environment variable
            INKVEC_NATIVE_ALPHA=0 turns the default off); false composites onto a matte
            first, as releases up to 0.1.3 did.
        cutout:
            With native_alpha off, carry the input's transparency into the SVG: a face
            the source drew transparent becomes a hole, one drawn at a single opacity
            keeps it as fill-opacity, and white artwork on a transparent ground
            survives. Changes nothing for an opaque input, and nothing with native_alpha
            on (the default), which already carries the transparency out.
        content_units:
            Scale the fit tolerances with the raster, so a large, simple drawing gets
            the parameter count of a small one. Trades fidelity for parsimony: small
            squares can come back as circles and thin rings broken.
        harmonize:
            Shape harmonization (on by default): marks that repeat across the drawing
            are redrawn from one consensus geometry per cluster, which saves parameters.
            A mark takes the consensus only where that stays within 0.1 px of the
            boundary traced for it and costs fewer parameters; a face another face is
            drawn against, and a fitted circle or rounded rectangle, is never moved. Set
            it to false to skip the pass.
        harmonize_threshold:
            Shape-equivalence threshold for harmonization: the outline similarity (IoU
            after affine normalisation) above which two marks count as the same shape.
            Must be >= 0 and <= 1.

    The SVG is byte-identical to ``trace`` on a PNG holding the same pixels.
    """
