/* tslint:disable */
/* eslint-disable */
export const __wbg_intake_free: (a: number, b: number) => void;
export const __wbg_wbg_rayon_poolbuilder_free: (a: number, b: number) => void;
export const build_target: () => [number, number];
export const default_options_json: () => [number, number];
export const denoiser_model_sha256: () => [number, number];
export const denoiser_model_url: () => [number, number];
export const denoiser_threshold: () => number;
export const initThreadPool: (a: number) => any;
export const intake_denoiser_input: (a: number) => [number, number];
export const intake_denoiser_input_size: (a: number) => [number, number];
export const intake_height: (a: number) => number;
export const intake_residual: (a: number, b: number, c: number) => [number, number];
export const intake_rgba8: (a: number) => [number, number];
export const intake_take_denoiser_output: (a: number, b: number, c: number) => [number, number];
export const intake_trace: (a: number) => [number, number, number, number];
export const intake_traceOnce: (a: number) => [number, number, number, number];
export const intake_width: (a: number) => number;
export const options_schema_json: () => [number, number];
export const prepare: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number) => [number, number, number];
export const threads_available: () => number;
export const trace: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number) => [number, number, number, number];
export const trace_json: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const trace_rgba_json: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const version: () => [number, number];
export const wbg_rayon_poolbuilder_build: (a: number) => void;
export const wbg_rayon_poolbuilder_numThreads: (a: number) => number;
export const wbg_rayon_poolbuilder_receiver: (a: number) => number;
export const wbg_rayon_start_worker: (a: number) => void;
export const memory: WebAssembly.Memory;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_thread_destroy: (a?: number, b?: number, c?: number) => void;
export const __wbindgen_start: (a: number) => void;
