<?php

/**
 * GENERATED by bindings/codegen/php.py from bindings/options.schema.json.
 *
 * Do not edit: change `inkvec::Options` in crates/inkvec, regenerate the schema
 * (cargo test -p inkvec), then run `python bindings/codegen/generate.py`.
 */

declare(strict_types=1);

namespace LogoLabs\Inkvec;

/**
 * Options for one trace, as named arguments:
 *
 *     Inkvec::trace($png, new Options(colors: 16, noBackground: true));
 *
 * Every property is optional and `null` by default, meaning "take the tracer's own default"
 * (`Inkvec::defaults()` reads their values from the library). Names and meanings are
 * `inkvec::Options`'s, read from the same JSON Schema (`Inkvec::optionsSchema()`) that
 * generated this class. The native library validates every value, so an unknown name or an
 * out-of-range value is an {@see InvalidOptionsException}, not a silent no-op -- and an
 * option added to Inkvec works before this class is regenerated for it, by passing an array
 * or a raw JSON string instead of an Options.
 */
final class Options
{
    /**
     * @param float|null $precision Sets the description-length cost of a coordinate, in
     *     pixels: lambda = ln(extent / precision). Smaller values buy more detail with more
     *     coordinates. It does not set the digits written; coordinates are always written at 2
     *     decimals. Range: > 0. The tracer's default is 0.1; leave it null to use that.
     *
     * @param float|null $minArea Discard features smaller than this area, in square pixels.
     *     Range: > 0. The tracer's default is 2.0; leave it null to use that.
     *
     * @param int|null $colors Maximum palette size. Range: >= 1 and <= 4096. The tracer's
     *     default is 64; leave it null to use that.
     *
     * @param float|null $merge OKLab distance below which two colours are treated as one ink.
     *     Range: >= 0. The tracer's default is 0.035; leave it null to use that.
     *
     * @param int|null $maxDim Inputs larger than this on their longer side, in pixels, are
     *     traced at this size and the SVG is written at the original size. Trace time grows with
     *     the pixel count. 0 means no cap. The tracer's default is 2048; leave it null to use
     *     that.
     *
     * @param float|null $timeBudget Advisory wall-clock budget, in seconds; 0 means none.
     *     Gradient-band merging stops at 60% of it and the boundary solve gets 25%; the output is
     *     still a correct trace, with more fills or a less polished outline. A nonzero budget
     *     makes the output depend on machine speed and load, so it is no longer reproducible.
     *     Range: >= 0. The tracer's default is 0.0; leave it null to use that.
     *
     * @param float|null $margin Transparent margin around the output, as a fraction of the
     *     larger side. The viewBox grows; the geometry does not move. Range: >= 0. The tracer's
     *     default is 0.0; leave it null to use that.
     *
     * @param bool|null $noBackground Knock the background out: the face that covers the whole
     *     canvas is not painted, so the artwork sits on transparency. The tracer's default is
     *     false; leave it null to use that.
     *
     * @param bool|null $minify No ids or groups, no trailing zeros. Same geometry, typically
     *     about a tenth smaller. The tracer's default is false; leave it null to use that.
     *
     * @param bool|null $nativeAlpha Trace transparency natively: each ink is a colour and an
     *     opacity, and the transparent ground is an ink of its own, instead of the image being
     *     composited onto a matte first. Holes stay holes, white artwork on a transparent ground
     *     traces, glows and shadows stay translucent, and a fade is one gradient of colour and
     *     opacity. An opaque input traces the same either way. On by default, as on the command
     *     line (where the environment variable INKVEC_NATIVE_ALPHA=0 turns the default off); false
     *     composites onto a matte first, as releases up to 0.1.3 did. The tracer's default is
     *     true; leave it null to use that.
     *
     * @param bool|null $cutout With native_alpha off, carry the input's transparency into the
     *     SVG: a face the source drew transparent becomes a hole, one drawn at a single opacity
     *     keeps it as fill-opacity, and white artwork on a transparent ground survives. Changes
     *     nothing for an opaque input, and nothing with native_alpha on (the default), which
     *     already carries the transparency out. The tracer's default is false; leave it null to
     *     use that.
     *
     * @param bool|null $contentUnits Scale the fit tolerances with the raster, so a large,
     *     simple drawing gets the parameter count of a small one. Trades fidelity for parsimony:
     *     small squares can come back as circles and thin rings broken. The tracer's default is
     *     false; leave it null to use that.
     *
     * @param bool|null $harmonize Shape harmonization (on by default): marks that repeat
     *     across the drawing are redrawn from one consensus geometry per cluster, which saves
     *     parameters. A mark takes the consensus only where that stays within 0.1 px of the
     *     boundary traced for it and costs fewer parameters; a face another face is drawn against,
     *     and a fitted circle or rounded rectangle, is never moved. Set it to false to skip the
     *     pass. The tracer's default is true; leave it null to use that.
     *
     * @param float|null $harmonizeThreshold Shape-equivalence threshold for harmonization: the
     *     outline similarity (IoU after affine normalisation) above which two marks count as the
     *     same shape. Range: >= 0 and <= 1. The tracer's default is 0.92; leave it null to use
     *     that.
     */
    public function __construct(
        public readonly ?float $precision = null,
        public readonly ?float $minArea = null,
        public readonly ?int $colors = null,
        public readonly ?float $merge = null,
        public readonly ?int $maxDim = null,
        public readonly ?float $timeBudget = null,
        public readonly ?float $margin = null,
        public readonly ?bool $noBackground = null,
        public readonly ?bool $minify = null,
        public readonly ?bool $nativeAlpha = null,
        public readonly ?bool $cutout = null,
        public readonly ?bool $contentUnits = null,
        public readonly ?bool $harmonize = null,
        public readonly ?float $harmonizeThreshold = null,
    ) {
    }

    /**
     * The options that were set, keyed by the name the tracer knows them under. An unset
     * option is absent, so the tracer applies its own default to it.
     *
     * @return array<string, bool|int|float>
     */
    public function toArray(): array
    {
        $set = [];
        if ($this->precision !== null) {
            $set['precision'] = $this->precision;
        }
        if ($this->minArea !== null) {
            $set['min_area'] = $this->minArea;
        }
        if ($this->colors !== null) {
            $set['colors'] = $this->colors;
        }
        if ($this->merge !== null) {
            $set['merge'] = $this->merge;
        }
        if ($this->maxDim !== null) {
            $set['max_dim'] = $this->maxDim;
        }
        if ($this->timeBudget !== null) {
            $set['time_budget'] = $this->timeBudget;
        }
        if ($this->margin !== null) {
            $set['margin'] = $this->margin;
        }
        if ($this->noBackground !== null) {
            $set['no_background'] = $this->noBackground;
        }
        if ($this->minify !== null) {
            $set['minify'] = $this->minify;
        }
        if ($this->nativeAlpha !== null) {
            $set['native_alpha'] = $this->nativeAlpha;
        }
        if ($this->cutout !== null) {
            $set['cutout'] = $this->cutout;
        }
        if ($this->contentUnits !== null) {
            $set['content_units'] = $this->contentUnits;
        }
        if ($this->harmonize !== null) {
            $set['harmonize'] = $this->harmonize;
        }
        if ($this->harmonizeThreshold !== null) {
            $set['harmonize_threshold'] = $this->harmonizeThreshold;
        }

        return $set;
    }

    /**
     * The same, as the JSON object the native library parses (`{}` when nothing is set).
     */
    public function toJson(): string
    {
        $set = $this->toArray();

        if ($set === []) {
            return '{}';
        }

        return json_encode($set, JSON_THROW_ON_ERROR | JSON_PRESERVE_ZERO_FRACTION);
    }
}
