"""C#: the generated options surface, `packages/dotnet/src/LogoLabs.Inkvec/InkvecOptions.generated.cs`.

Every option becomes a nullable property on `InkvecOptions`: `null` means "take the
tracer's default", so the class itself never hard-codes a default value (those live only in
Rust). `ToJson()` writes just the properties that were set, which is what
`inkvec_trace`/`inkvec_trace_rgba` read; nothing in this file or the rest of the binding
restates an option's name, type, range or default by hand.
"""

from __future__ import annotations

import textwrap
from pathlib import Path

from schema import ROOT, Option

OUT = ROOT / "packages" / "dotnet" / "src" / "LogoLabs.Inkvec" / "InkvecOptions.generated.cs"

# C# nullable property type and the JSON-value expression for a set property, keyed by the
# schema's JSON Schema type. `{0}` is the property's (non-null) value expression.
CS_TYPES = {"boolean": "bool", "integer": "int", "number": "double"}
JSON_VALUE = {
    "boolean": "{0} ? \"true\" : \"false\"",
    "integer": "{0}.ToString(CultureInfo.InvariantCulture)",
    "number": "{0}.ToString(\"R\", CultureInfo.InvariantCulture)",
}

HEADER = """\
// <auto-generated/>
// GENERATED by bindings/codegen/csharp.py from bindings/options.schema.json.
// Do not edit: change `inkvec::Options` in crates/inkvec, regenerate the schema
// (cargo test -p inkvec), then run `python bindings/codegen/generate.py`.

using System.Globalization;
using System.Text;

namespace LogoLabs.Inkvec
{
    /// <summary>
    /// Options for one Inkvec trace. Every property is optional and defaults to
    /// <see langword="null"/>, meaning "take the tracer's own default" (see
    /// <see cref="Inkvec.Defaults"/> for their values). Names and meanings are
    /// <c>inkvec::Options</c>'s, read from the same JSON Schema
    /// (<see cref="Inkvec.OptionsSchema"/>) that generated this class; the native library
    /// validates every value, so an unrecognised name is an
    /// <see cref="InvalidOptionsException"/> rather than a silent no-op.
    /// </summary>
    public sealed class InkvecOptions
    {
"""

FOOTER = """\
        /// <summary>
        /// Serialises the properties that have been set to the JSON object the native
        /// library reads. A property left <see langword="null"/> is left out, so the
        /// tracer applies its own default to it.
        /// </summary>
        public string ToJson()
        {
            var sb = new StringBuilder();
            sb.Append('{');
            var first = true;
"""

TAIL = """\
            sb.Append('}');
            return sb.ToString();
        }
    }
}
"""


def _pascal(name: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in name.split("_"))


def _summary(o: Option) -> str:
    paragraphs = [o.description]
    rng = o.range_text()
    extra = f"Range: {rng}." if rng else ""
    if extra:
        paragraphs.append(extra)
    paragraphs.append(f"The tracer's default is {_default_text(o)}; leave this null to use it.")
    lines: list[str] = []
    for p in paragraphs:
        wrapped = textwrap.wrap(p.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"), width=92)
        lines.extend(wrapped or [""])
    body = "\n".join(f"        /// {line}" for line in lines)
    return f"        /// <summary>\n{body}\n        /// </summary>\n"


def _default_text(o: Option) -> str:
    if o.kind == "boolean":
        return "true" if o.default else "false"
    if o.kind == "integer":
        return str(int(o.default))
    return repr(float(o.default))


def render(options: list[Option]) -> dict[Path, str]:
    props = []
    writes = []
    for o in options:
        prop = _pascal(o.name)
        cs_type = CS_TYPES[o.kind]
        props.append(f"{_summary(o)}        public {cs_type}? {prop} {{ get; set; }}\n")
        value_expr = JSON_VALUE[o.kind].format(f"{prop}.Value")
        writes.append(
            f'            if ({prop}.HasValue)\n'
            f'            {{\n'
            f'                if (!first) sb.Append(\',\');\n'
            f'                first = false;\n'
            f'                sb.Append("\\"{o.name}\\":").Append({value_expr});\n'
            f'            }}\n'
        )
    body = HEADER + "\n".join(props) + "\n" + FOOTER + "".join(writes) + TAIL
    return {OUT: body}
