"""C#: the generated options surface, `packages/dotnet/src/LogoLabs.Inkvec/InkvecOptions.generated.cs`.

Every option becomes a nullable property on `InkvecOptions`: `null` means "take the
tracer's default", so the class itself never hard-codes a default value (those live only in
Rust). `ToJson()` writes just the properties that were set, which is what
`inkvec_trace`/`inkvec_trace_rgba` read; nothing in this file or the rest of the binding
restates an option's name, type, range or default by hand.
"""

from __future__ import annotations

import json
import textwrap
from pathlib import Path

from schema import ROOT, Option

OUT = ROOT / "packages" / "dotnet" / "src" / "LogoLabs.Inkvec" / "InkvecOptions.generated.cs"

# C# property type (written nullable, `int?` / `string?`) and the JSON-value expression for a
# set property, keyed by the schema's JSON Schema type. `{0}` is the property's (non-null)
# value expression. A value type is tested with `.HasValue` and read with `.Value`; a
# reference type (string) is tested against null and read as is.
CS_TYPES = {"boolean": "bool", "integer": "int", "number": "double", "string": "string"}
VALUE_TYPES = {"boolean", "integer", "number"}
JSON_VALUE = {
    "boolean": "{0} ? \"true\" : \"false\"",
    "integer": "{0}.ToString(CultureInfo.InvariantCulture)",
    "number": "{0}.ToString(\"R\", CultureInfo.InvariantCulture)",
    "string": "JsonString({0})",
}

HEADER = """\
// <auto-generated/>
// GENERATED by bindings/codegen/csharp.py from bindings/options.schema.json.
// Do not edit: change `inkvec::Options` in crates/inkvec, regenerate the schema
// (cargo test -p inkvec), then run `python bindings/codegen/generate.py`.

// Generated code is outside the nullable context unless it opts in; without this a `string?`
// property would be oblivious to callers that enable nullable reference types.
#nullable enable

using System.Globalization;
using System.Text;

namespace LogoLabs.Inkvec
{
    /// <summary>
    /// Options for one Inkvec trace. Every property is optional and defaults to
    /// <see langword="null"/>, meaning "take the tracer's own default" (see
    /// <see cref="Inkvec.Defaults"/> for their values). Names and meanings are
    /// <c>inkvec::Options</c>'s, read from the same JSON Schema
    /// (<see cref="Inkvec.OptionsSchema"/>) that generated this class; the native library
    /// validates every value, so an unrecognised name is an
    /// <see cref="InvalidOptionsException"/> rather than a silent no-op.
    /// </summary>
    public sealed class InkvecOptions
    {
"""

FOOTER = """\
        /// <summary>
        /// Serialises the properties that have been set to the JSON object the native
        /// library reads. A property left <see langword="null"/> is left out, so the
        /// tracer applies its own default to it.
        /// </summary>
        public string ToJson()
        {
            var sb = new StringBuilder();
            sb.Append('{');
            var first = true;
"""

TAIL = """\
            sb.Append('}');
            return sb.ToString();
        }
"""

# Written only when some option is a string, so the class has no unused member otherwise.
# A raw string: the C# below is exactly what lands in the generated file.
JSON_STRING = r"""
        /// <summary>
        /// <paramref name="s"/> as a JSON string literal: quoted, with <c>"</c>, <c>\</c> and
        /// every control character escaped.
        /// </summary>
        private static string JsonString(string s)
        {
            var sb = new StringBuilder(s.Length + 2);
            sb.Append('"');
            foreach (var c in s)
            {
                switch (c)
                {
                    case '"': sb.Append("\\\""); break;
                    case '\\': sb.Append("\\\\"); break;
                    case '\n': sb.Append("\\n"); break;
                    case '\r': sb.Append("\\r"); break;
                    case '\t': sb.Append("\\t"); break;
                    default:
                        if (c < ' ')
                        {
                            sb.Append("\\u").Append(((int)c).ToString("x4", CultureInfo.InvariantCulture));
                        }
                        else
                        {
                            sb.Append(c);
                        }
                        break;
                }
            }
            sb.Append('"');
            return sb.ToString();
        }
"""

END = """\
    }
}
"""


def _pascal(name: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in name.split("_"))


def _summary(o: Option) -> str:
    paragraphs = [o.description]
    rng = o.range_text()
    extra = f"Range: {rng}." if rng else ""
    if extra:
        paragraphs.append(extra)
    paragraphs.append(f"The tracer's default is {_default_text(o)}; leave this null to use it.")
    lines: list[str] = []
    for p in paragraphs:
        wrapped = textwrap.wrap(p.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"), width=92)
        lines.extend(wrapped or [""])
    body = "\n".join(f"        /// {line}" for line in lines)
    return f"        /// <summary>\n{body}\n        /// </summary>\n"


def _default_text(o: Option) -> str:
    if o.kind == "boolean":
        return "true" if o.default else "false"
    if o.kind == "integer":
        return str(int(o.default))
    if o.kind == "string":
        return json.dumps(o.default)
    return repr(float(o.default))


def render(options: list[Option]) -> dict[Path, str]:
    props = []
    writes = []
    for o in options:
        prop = _pascal(o.name)
        nullable = o.kind in VALUE_TYPES
        cs_type = CS_TYPES[o.kind] + "?"
        props.append(f"{_summary(o)}        public {cs_type} {prop} {{ get; set; }}\n")
        value_expr = JSON_VALUE[o.kind].format(f"{prop}.Value" if nullable else prop)
        is_set = f"{prop}.HasValue" if nullable else f"{prop} != null"
        writes.append(
            f'            if ({is_set})\n'
            f'            {{\n'
            f'                if (!first) sb.Append(\',\');\n'
            f'                first = false;\n'
            f'                sb.Append("\\"{o.name}\\":").Append({value_expr});\n'
            f'            }}\n'
        )
    helper = JSON_STRING if any(o.kind == "string" for o in options) else ""
    body = HEADER + "\n".join(props) + "\n" + FOOTER + "".join(writes) + TAIL + helper + END
    return {OUT: body}
