"""Go: the `Options` struct of the Go module, `packages/go/options_generated.go`.

Every option becomes a pointer field -- nil means "use the Rust default" -- with its JSON
name as the tag and its description, range and default in the doc comment. The struct is
marshalled to JSON and parsed by `inkvec::Options::from_json` inside the WebAssembly module,
which applies the defaults and checks every value; nothing in Go restates either.
"""

from __future__ import annotations

import json
import textwrap
from pathlib import Path

from schema import ROOT, Option

OUT = ROOT / "packages" / "go" / "options_generated.go"

GO_TYPES = {"boolean": "bool", "integer": "int", "number": "float64", "string": "string"}

# Words Go spells in capitals inside an identifier (`MaxDPI`, not `MaxDpi`).
INITIALISMS = {"api", "dpi", "id", "json", "rgb", "rgba", "svg", "url", "utf8"}

HEADER = """\
// Code generated by bindings/codegen/golang.py from bindings/options.schema.json. DO NOT EDIT.
//
// Change `inkvec::Options` in crates/inkvec, regenerate the schema (cargo test -p inkvec),
// then run `python bindings/codegen/generate.py`.

package inkvec

// Options for one trace. Every field is optional: nil takes the default. Names and meanings
// are the Rust library's (`inkvec::Options`); the options travel to it as one JSON object,
// which it checks in full, so an unknown name or a value out of range is an
// ErrInvalidOptions rather than a silent no-op. Set a field with [Ptr]:
//
//	opts := &inkvec.Options{Colors: inkvec.Ptr(16), NoBackground: inkvec.Ptr(true)}
//
// An option newer than this struct can be passed with [TraceJSON].
type Options struct {
"""


def go_name(name: str) -> str:
    """`max_dim` -> `MaxDim`; initialisms in capitals."""
    parts = [p for p in name.split("_") if p]
    if not parts:
        raise SystemExit(f"option name {name!r} has no Go spelling")
    out = "".join(p.upper() if p in INITIALISMS else p[:1].upper() + p[1:] for p in parts)
    if not out.isidentifier() or not out[0].isalpha():
        raise SystemExit(f"option name {name!r} has no Go spelling (got {out!r})")
    return out


def _default(o: Option) -> str:
    if o.kind == "boolean":
        return "true" if o.default else "false"
    if o.kind == "integer":
        return str(int(o.default))
    if o.kind == "string":
        return json.dumps(o.default)
    return json.dumps(float(o.default))


def _doc(o: Option) -> str:
    paragraphs = [o.description]
    rng = o.range_text()
    if o.kind == "integer":
        paragraphs.append(f"An integer{' ' + rng if rng else ''}. Default: {_default(o)}.")
    elif rng:
        paragraphs.append(f"A number {rng}. Default: {_default(o)}.")
    else:
        paragraphs.append(f"Default: {_default(o)}.")
    lines: list[str] = []
    for i, p in enumerate(paragraphs):
        if i:
            lines.append("")
        lines.extend(textwrap.wrap(p, width=88) or [""])
    return "".join(f"\t// {line}\n" if line else "\t//\n" for line in lines)


def render(options: list[Option]) -> dict[Path, str]:
    names = [go_name(o.name) for o in options]
    dupes = {n for n in names if names.count(n) > 1}
    if dupes:
        raise SystemExit(f"options collide as Go fields: {sorted(dupes)}")
    fields = "\n".join(
        f"{_doc(o)}\t{n} *{GO_TYPES[o.kind]} `json:\"{o.name},omitempty\"`\n"
        for o, n in zip(options, names)
    )
    return {OUT: HEADER + fields + "}\n"}
