"""Java: the typed options surface, `packages/java/src/main/java/com/logolabs/inkvec/InkvecOptions.java`.

Every option becomes a field with a fluent builder setter, its javadoc, default and range
taken straight from the schema. `InkvecOptions.toJson()` walks the same list to write the
JSON object the C ABI (and every other binding) takes; nothing here restates a default or a
range anywhere else, and no validation happens in Java -- `Options::from_json` in Rust is the
only place a value is checked.
"""

from __future__ import annotations

import json
import textwrap
from pathlib import Path

from schema import ROOT, Option

OUT = ROOT / "packages" / "java" / "src" / "main" / "java" / "com" / "logolabs" / "inkvec" / "InkvecOptions.java"

JAVA_TYPES = {"boolean": "boolean", "integer": "int", "number": "double", "string": "String"}

# Written only when some option is a string, so the class has no unused member otherwise.
# A raw string: the Java below is exactly what lands in the generated file. A null String is
# written as JSON null, which the tracer rejects as invalid options -- Rust stays the only
# place a value is checked.
JSON_STRING = r"""
    /**
     * {@code s} as a JSON string literal: quoted, with {@code "}, the backslash and every
     * control character escaped; {@code null} as JSON {@code null}.
     */
    private static String jsonString(String s) {
        if (s == null) {
            return "null";
        }
        StringBuilder sb = new StringBuilder(s.length() + 2);
        sb.append('"');
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            switch (c) {
                case '"':
                    sb.append("\\\"");
                    break;
                case '\\':
                    sb.append("\\\\");
                    break;
                case '\n':
                    sb.append("\\n");
                    break;
                case '\r':
                    sb.append("\\r");
                    break;
                case '\t':
                    sb.append("\\t");
                    break;
                default:
                    if (c < 0x20) {
                        sb.append(String.format("\\u%04x", (int) c));
                    } else {
                        sb.append(c);
                    }
            }
        }
        return sb.append('"').toString();
    }
"""

HEADER = """\
// GENERATED by bindings/codegen/java.py from bindings/options.schema.json.
// Do not edit: change `inkvec::Options` in crates/inkvec, regenerate the schema
// (cargo test -p inkvec), then run `python bindings/codegen/generate.py`.
package com.logolabs.inkvec;

/**
 * Options for one Inkvec trace. Every field is optional and takes its default when missing.
 * Names and meanings are the Rust library's ({@code inkvec::Options}); the tracer checks
 * every value against {@link #toJson()}, and an unknown name is an error rather than a
 * silent no-op.
 *
 * <p>Immutable. Start from {@link #defaults()} or {@link #builder()}; every builder field
 * begins at its Rust default, so setting none of them reproduces {@link #defaults()}.
 */
public final class InkvecOptions {
"""


def _camel(name: str) -> str:
    head, *rest = name.split("_")
    return head + "".join(p[:1].upper() + p[1:] for p in rest)


def _literal(o: Option) -> str:
    if o.kind == "boolean":
        return "true" if o.default else "false"
    if o.kind == "integer":
        return str(int(o.default))
    if o.kind == "string":
        # JSON's escapes are Java's, and json.dumps writes \n and \r (never \u000a or
        # \u000d, which Java would unescape into a line break before lexing the literal).
        return json.dumps(o.default)
    return repr(float(o.default)) +("" if "." in repr(float(o.default)) or "e" in repr(float(o.default)) else ".0")


def _javadoc(o: Option, indent: str) -> str:
    paragraphs = [o.description]
    rng = o.range_text()
    if o.kind == "integer":
        paragraphs.append(f"An integer{' ' + rng if rng else ''}.")
    elif rng:
        paragraphs.append(f"A number {rng}.")
    lines: list[str] = []
    for i, p in enumerate(paragraphs):
        if i:
            lines.append("")
        escaped = p.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        lines.extend(textwrap.wrap(escaped, width=92) or [""])
    lines.append("")
    lines.append(f"@default {json.dumps(o.default)}")
    body = "\n".join(f"{indent} * {line}" if line else f"{indent} *" for line in lines)
    return f"{indent}/**\n{body}\n{indent} */\n"


def render(options: list[Option]) -> dict[Path, str]:
    fields = [(o, _camel(o.name)) for o in options]

    out = [HEADER]
    for o, camel in fields:
        out.append(f"    private final {JAVA_TYPES[o.kind]} {camel};\n")
    out.append("\n    private InkvecOptions(Builder b) {\n")
    for o, camel in fields:
        out.append(f"        this.{camel} = b.{camel};\n")
    out.append("    }\n")

    out.append(
        "\n    /** Every option at its default -- the command line's defaults. */\n"
        "    public static InkvecOptions defaults() {\n"
        "        return new Builder().build();\n"
        "    }\n"
    )
    out.append(
        "\n    /** A builder with every field starting at its default. */\n"
        "    public static Builder builder() {\n"
        "        return new Builder();\n"
        "    }\n"
    )

    for o, camel in fields:
        out.append(f"\n{_javadoc(o, '    ')}")
        out.append(f"    public {JAVA_TYPES[o.kind]} {camel}() {{\n        return {camel};\n    }}\n")

    out.append(
        "\n    /**\n"
        "     * The JSON object the C ABI, and every other Inkvec binding, take as options.\n"
        "     * Every field is written explicitly, so this is equivalent to passing only the\n"
        "     * fields that differ from {@link #defaults()}.\n"
        "     */\n"
        "    public String toJson() {\n"
        "        StringBuilder sb = new StringBuilder(256);\n"
        "        sb.append('{');\n"
    )
    for i, (o, camel) in enumerate(fields):
        sep = "" if i == 0 else ","
        value = f"jsonString({camel})" if o.kind == "string" else camel
        out.append(f'        sb.append("{sep}\\"{o.name}\\":").append({value});\n')
    out.append("        sb.append('}');\n        return sb.toString();\n    }\n")
    if any(o.kind == "string" for o in options):
        out.append(JSON_STRING)

    out.append(
        "\n    @Override\n"
        "    public String toString() {\n"
        "        return toJson();\n"
        "    }\n"
    )

    out.append(
        "\n    /**\n"
        "     * Builds an {@link InkvecOptions}. Every field starts at its Rust default; call\n"
        "     * only the setters you need to change.\n"
        "     */\n"
        "    public static final class Builder {\n"
    )
    for o, camel in fields:
        out.append(f"        private {JAVA_TYPES[o.kind]} {camel} = {_literal(o)};\n")
    out.append("\n        private Builder() {\n        }\n")
    for o, camel in fields:
        out.append(f"\n{_javadoc(o, '        ')}")
        out.append(
            f"        public Builder {camel}({JAVA_TYPES[o.kind]} {camel}) {{\n"
            f"            this.{camel} = {camel};\n"
            f"            return this;\n"
            f"        }}\n"
        )
    out.append(
        "\n        /** Builds the immutable {@link InkvecOptions}. */\n"
        "        public InkvecOptions build() {\n"
        "            return new InkvecOptions(this);\n"
        "        }\n"
        "    }\n"
    )

    out.append("}\n")
    return {OUT: "".join(out)}
