"""PHP: the typed options of the Composer package, `packages/php/src/Options.php`.

Every option becomes a nullable, readonly constructor property -- `null` means "take the
tracer's default" -- so the class never hard-codes a default (those live only in Rust).
`toArray()` keeps the properties that were set and `toJson()` writes them as the JSON object
the C ABI reads; nothing here or elsewhere in the binding restates an option's name, type,
range or default.
"""

from __future__ import annotations

import textwrap
from pathlib import Path

from schema import ROOT, Option

# PSR-4 ties the class name to the file name, so this one cannot be marked
# `.generated` the way the C# and TypeScript files are; the header says it instead.
OUT = ROOT / "packages" / "php" / "src" / "Options.php"

PHP_TYPES = {"boolean": "bool", "integer": "int", "number": "float"}

HEADER = """\
<?php

/**
 * GENERATED by bindings/codegen/php.py from bindings/options.schema.json.
 *
 * Do not edit: change `inkvec::Options` in crates/inkvec, regenerate the schema
 * (cargo test -p inkvec), then run `python bindings/codegen/generate.py`.
 */

declare(strict_types=1);

namespace LogoLabs\\Inkvec;

/**
 * Options for one trace, as named arguments:
 *
 *     Inkvec::trace($png, new Options(colors: 16, noBackground: true));
 *
 * Every property is optional and `null` by default, meaning "take the tracer's own default"
 * (`Inkvec::defaults()` reads their values from the library). Names and meanings are
 * `inkvec::Options`'s, read from the same JSON Schema (`Inkvec::optionsSchema()`) that
 * generated this class. The native library validates every value, so an unknown name or an
 * out-of-range value is an {@see InvalidOptionsException}, not a silent no-op -- and an
 * option added to Inkvec works before this class is regenerated for it, by passing an array
 * or a raw JSON string instead of an Options.
 */
final class Options
{
"""


def _wrap(text: str, indent: str, width: int = 96) -> list[str]:
    lines = textwrap.wrap(text.replace("*/", "*\\/"), width=width - len(indent) - 3)
    return [f"{indent}* {line}" if line else f"{indent}*" for line in lines or [""]]


def _camel(name: str) -> str:
    head, *rest = name.split("_")
    return head + "".join(part[:1].upper() + part[1:] for part in rest)


def _default_text(o: Option) -> str:
    if o.kind == "boolean":
        return "true" if o.default else "false"
    if o.kind == "integer":
        return str(int(o.default))
    return repr(float(o.default))


def _param_doc(o: Option) -> list[str]:
    """One `@param` entry: description, range, and the default left to the tracer."""
    parts = [o.description]
    rng = o.range_text()
    if rng:
        parts.append(f"Range: {rng}.")
    parts.append(f"The tracer's default is {_default_text(o)}; leave it null to use that.")
    text = f"@param {PHP_TYPES[o.kind]}|null ${_camel(o.name)} " + " ".join(parts)
    lines = _wrap(text, "     ")
    # Continuation lines of an @param read better indented under the description.
    return [lines[0]] + [f"     *     {line.lstrip('* ').rstrip()}" if line.strip() != "*" else line for line in lines[1:]]


def render(options: list[Option]) -> dict[Path, str]:
    doc = ["    /**"]
    for i, o in enumerate(options):
        if i:
            doc.append("     *")
        doc.extend(_param_doc(o))
    doc.append("     */")

    params = [
        f"        public readonly ?{PHP_TYPES[o.kind]} ${_camel(o.name)} = null," for o in options
    ]

    sets = []
    for o in options:
        prop = _camel(o.name)
        sets.append(
            f"        if ($this->{prop} !== null) {{\n"
            f"            $set['{o.name}'] = $this->{prop};\n"
            f"        }}\n"
        )

    body = (
        HEADER
        + "\n".join(doc)
        + "\n    public function __construct(\n"
        + "\n".join(params)
        + "\n    ) {\n    }\n"
        + """
    /**
     * The options that were set, keyed by the name the tracer knows them under. An unset
     * option is absent, so the tracer applies its own default to it.
     *
     * @return array<string, bool|int|float>
     */
    public function toArray(): array
    {
        $set = [];
"""
        + "".join(sets)
        + """
        return $set;
    }

    /**
     * The same, as the JSON object the native library parses (`{}` when nothing is set).
     */
    public function toJson(): string
    {
        $set = $this->toArray();

        if ($set === []) {
            return '{}';
        }

        return json_encode($set, JSON_THROW_ON_ERROR | JSON_PRESERVE_ZERO_FRACTION);
    }
}
"""
    )
    return {OUT: body}
