"""Python: the type stub `crates/inkvec-py/python/inkvec/__init__.pyi`.

Every option becomes a typed keyword argument with its default and description on `trace`
and `trace_rgba`. The rest of the stub -- the functions, `Traced`, the exceptions -- is the
Python API's own shape and is written out below; it changes only when that API does.
"""

from __future__ import annotations

import json
import textwrap
from pathlib import Path

from schema import ROOT, Option

TARGET = ROOT / "crates" / "inkvec-py" / "python" / "inkvec" / "__init__.pyi"

# Positional parameters of trace / trace_rgba; an option with one of these names would
# collide with them.
RESERVED = {"image", "pixels", "width", "height"}

PY_TYPES = {"boolean": "bool", "integer": "int", "number": "float", "string": "str"}

HEADER = '''\
# GENERATED by bindings/codegen/python_stub.py from bindings/options.schema.json.
# Do not edit: run `python bindings/codegen/generate.py` instead.
"""Inkvec: raster logos, icons and illustrations to compact, accurate SVG."""

from __future__ import annotations

import os
from typing import IO, Any, Dict, Optional, Union

__version__: str

#: Encoded image bytes, a path to an image file, a binary file object, a Pillow image, or
#: a uint8 numpy array of shape (H, W), (H, W, 3) or (H, W, 4).
ImageInput = Union[bytes, bytearray, memoryview, str, "os.PathLike[str]", IO[bytes], Any]

class InkvecError(Exception):
    """Base class of every error Inkvec raises."""

class InvalidImageError(InkvecError):
    """The input is not a decodable image, or raw pixels do not match the size given."""

class InvalidOptionsError(InkvecError):
    """An option is unknown, of the wrong type, or out of range."""

class InternalError(InkvecError):
    """The tracer failed. Not the caller's fault; worth a bug report."""

class Traced:
    """A finished trace. ``str(traced)`` is the SVG document."""

    @property
    def svg(self) -> str:
        """The SVG document."""
    @property
    def width(self) -> int:
        """Width of the input image, in pixels."""
    @property
    def height(self) -> int:
        """Height of the input image, in pixels."""
    def _repr_svg_(self) -> str: ...

def options_schema() -> Dict[str, Any]:
    """The JSON Schema of the options: every name, type, default, description and range."""

def defaults() -> Dict[str, Any]:
    """Every option at its default."""

def build_target() -> str:
    """The target the native library was compiled for, e.g. ``"x86_64-linux-gnu"``.

    Output is byte-identical between builds with the same target; another target can write
    the same drawing slightly differently (subpaths in another order, a last digit).
    """
'''


def _literal(o: Option) -> str:
    if o.kind == "boolean":
        return "True" if o.default else "False"
    if o.kind == "integer":
        return str(int(o.default))
    if o.kind == "string":
        # JSON's escapes (\" \\ \n \uXXXX ...) are all valid in a Python string literal.
        return json.dumps(o.default)
    return repr(float(o.default))


def _params(options: list[Option]) -> str:
    return "".join(f"    {o.name}: {PY_TYPES[o.kind]} = {_literal(o)},\n" for o in options)


def _arg_docs(options: list[Option]) -> str:
    out = []
    for o in options:
        text = o.description
        rng = o.range_text()
        if rng:
            text += f" Must be {rng}."
        body = textwrap.fill(
            text, width=88, initial_indent=" " * 12, subsequent_indent=" " * 12
        )
        out.append(f"        {o.name}:\n{body}\n")
    return "".join(out)


def render(options: list[Option]) -> dict[Path, str]:
    clash = RESERVED & {o.name for o in options}
    if clash:
        raise SystemExit(f"option name(s) {sorted(clash)} collide with trace() parameters")
    params, docs = _params(options), _arg_docs(options)
    trace = f'''
def trace(
    image: ImageInput,
    *,
{params}) -> Traced:
    """Trace an image to SVG.

    Args:
        image: Encoded image bytes (PNG, JPEG, WebP, GIF, BMP or TIFF), a path to such a
            file, a binary file object, a Pillow image, or a uint8 numpy array of shape
            (H, W), (H, W, 3) or (H, W, 4).
{docs}
    Raises:
        InvalidImageError: the input cannot be decoded.
        InvalidOptionsError: an option is unknown, of the wrong type, or out of range.
        InternalError: the tracer failed.
    """

def trace_rgba(
    pixels: Any,
    width: Optional[int] = None,
    height: Optional[int] = None,
    *,
{params}) -> Traced:
    """Trace raw straight-RGBA8 pixels (row-major, tightly packed) to SVG.

    Args:
        pixels: A bytes-like buffer of exactly width * height * 4 bytes, or a Pillow image
            or uint8 numpy array (then width and height are read from it).
        width: Width in pixels; required for a flat buffer.
        height: Height in pixels; required for a flat buffer.
{docs}
    The SVG is byte-identical to ``trace`` on a PNG holding the same pixels.
    """
'''
    return {TARGET: HEADER + trace}
