"""Swift: the options struct of the Swift package and its copy of the C header.

`packages/swift/Sources/Inkvec/InkvecOptions.generated.swift` -- every option becomes an
optional property of `InkvecOptions` (nil = the tracer's default) with a camelCase name, its
description, range and default in the doc comment, and a `CodingKey` that is the schema's
snake_case name. The struct is encoded to JSON and parsed by `inkvec::Options::from_json`,
which applies the defaults and checks every value; nothing in Swift restates either.

`packages/swift/Sources/InkvecFFI/inkvec.h` -- the C module's header, a verbatim copy of
`crates/inkvec-ffi/include/inkvec.h` (which cbindgen generates). SwiftPM needs the header
inside the package; writing the copy here makes `generate.py --check` fail the moment the
two differ.
"""

from __future__ import annotations

import json
import re
import textwrap
from pathlib import Path

from schema import ROOT, Option

PACKAGE = ROOT / "packages" / "swift"
OUT = PACKAGE / "Sources" / "Inkvec" / "InkvecOptions.generated.swift"
HEADER_SOURCE = ROOT / "crates" / "inkvec-ffi" / "include" / "inkvec.h"
HEADER_COPY = PACKAGE / "Sources" / "InkvecFFI" / "inkvec.h"

SWIFT_TYPES = {"boolean": "Bool", "integer": "Int", "number": "Double"}

# Swift's reserved words; an option named like one is written in backticks.
KEYWORDS = set(
    """
    associatedtype class deinit enum extension fileprivate func import init inout internal let
    open operator private precedencegroup protocol public rethrows static struct subscript
    typealias var break case catch continue default defer do else fallthrough for guard if in
    repeat return throw switch where while Any as await false is nil self Self super throws true
    try
    """.split()
)

# Members InkvecOptions already has (Codable, Hashable, and `jsonString()` in Inkvec.swift),
# and names a member cannot have (`x.self` is `x`); an option with one of these Swift names
# is refused. Other keywords are written in backticks.
RESERVED = {"jsonString", "hashValue", "hash", "encode", "self", "init"}

WIDTH = 88  # doc-comment text, after the indent and `/// `

HEADER = """\
// GENERATED by bindings/codegen/swift.py from bindings/options.schema.json.
// Do not edit: change `inkvec::Options` in crates/inkvec, regenerate the schema
// (cargo test -p inkvec), then run `python bindings/codegen/generate.py`.

/// Options for one trace.
///
/// Every property is optional. `nil` leaves the option out of the JSON the tracer receives,
/// so it takes the Rust library's default (`Inkvec.defaults` reads them all). Names and
/// meanings are `inkvec::Options`'s; the tracer checks every value, and a value of the wrong
/// type or out of range is an `InkvecError.invalidOptions` that names the option.
///
/// ```swift
/// var options = InkvecOptions(colors: 16)
/// options.noBackground = true
/// let traced = try Inkvec.trace(png, options: options)
/// ```
public struct InkvecOptions: Codable, Hashable, Sendable {
"""


def swift_name(option: str) -> str:
    """`min_area` -> `minArea`; the schema's names are snake_case identifiers."""
    if not re.fullmatch(r"[a-z][a-z0-9_]*", option):
        raise SystemExit(f"option `{option}` is not a snake_case identifier; teach bindings/codegen/swift.py")
    head, *rest = [p for p in option.split("_") if p]
    return head + "".join(p[0].upper() + p[1:] for p in rest)


def _ident(name: str) -> str:
    return f"`{name}`" if name in KEYWORDS else name


def _default(o: Option) -> str:
    if o.kind == "boolean":
        return "true" if o.default else "false"
    if o.kind == "integer":
        return str(int(o.default))
    return json.dumps(float(o.default))


def _doc(o: Option, indent: str) -> str:
    rng = o.range_text()
    if o.kind == "integer":
        facts = f"An integer{' ' + rng if rng else ''}. "
    elif rng:
        facts = f"A number {rng}. "
    else:
        facts = ""
    paragraphs = [o.description, f"{facts}Default: `{_default(o)}`."]
    lines: list[str] = []
    for i, p in enumerate(paragraphs):
        if i:
            lines.append("")
        lines.extend(textwrap.wrap(p, width=WIDTH) or [""])
    return "".join(f"{indent}///{' ' + line if line else ''}\n" for line in lines)


def render_options(options: list[Option]) -> str:
    names = [swift_name(o.name) for o in options]
    dupes = {n for n in names if names.count(n) > 1}
    if dupes:
        raise SystemExit(f"options map to the same Swift name: {sorted(dupes)}")
    clash = RESERVED & set(names)
    if clash:
        raise SystemExit(f"option(s) {sorted(clash)} collide with members of InkvecOptions")
    props = "\n".join(
        f"{_doc(o, '    ')}    public var {_ident(n)}: {SWIFT_TYPES[o.kind]}?\n" for o, n in zip(options, names)
    )
    params = ",\n".join(f"        {_ident(n)}: {SWIFT_TYPES[o.kind]}? = nil" for o, n in zip(options, names))
    assigns = "".join(f"        self.{n} = {_ident(n)}\n" for n in names)
    keys = "".join(
        f"        case {_ident(n)}\n" if n == o.name else f'        case {_ident(n)} = "{o.name}"\n'
        for o, n in zip(options, names)
    )
    init = (
        "    /// Options with the given values; every option left out (nil) takes its default.\n"
        f"    public init(\n{params}\n    ) {{\n{assigns}    }}\n"
    )
    coding = f"    enum CodingKeys: String, CodingKey {{\n{keys}    }}\n" if options else ""
    return HEADER + props + "\n" + init + ("\n" + coding if coding else "") + "}\n"


def render(options: list[Option]) -> dict[Path, str]:
    header = HEADER_SOURCE.read_text(encoding="utf-8").replace("\r\n", "\n")
    return {OUT: render_options(options), HEADER_COPY: header}
