"""TypeScript: the `Options` interface of the npm package, `packages/npm/src/options.generated.ts`.

Every option becomes an optional property with its description, range and default in the
doc comment, so an editor shows the same text the Rust docs do. The object is passed to the
WebAssembly as JSON and parsed by `inkvec::Options::from_json`, which applies the defaults
and checks every value; nothing in TypeScript restates either.
"""

from __future__ import annotations

import json
import textwrap
from pathlib import Path

from schema import ROOT, Option

OUT = ROOT / "packages" / "npm" / "src" / "options.generated.ts"

TS_TYPES = {"boolean": "boolean", "integer": "number", "number": "number", "string": "string"}

HEADER = """\
// GENERATED by bindings/codegen/typescript.py from bindings/options.schema.json.
// Do not edit: change `inkvec::Options` in crates/inkvec, regenerate the schema
// (cargo test -p inkvec), then run `python bindings/codegen/generate.py`.

/**
 * Options for one trace. Every field is optional and takes its default when missing.
 * Names and meanings are the Rust library's (`inkvec::Options`); the tracer checks every
 * value, and an unknown name is an error rather than a silent no-op.
 */
export interface Options {
"""


def _doc(o: Option) -> str:
    paragraphs = [o.description]
    rng = o.range_text()
    if o.kind == "integer":
        paragraphs.append(f"An integer{' ' + rng if rng else ''}.")
    elif rng:
        paragraphs.append(f"A number {rng}.")
    paragraphs.append(f"@default {json.dumps(o.default)}")
    lines: list[str] = []
    for i, p in enumerate(paragraphs):
        if i:
            lines.append("")
        lines.extend(textwrap.wrap(p.replace("*/", "*\\/"), width=86) or [""])
    body = "\n".join(f"   * {line}" if line else "   *" for line in lines)
    return f"  /**\n{body}\n   */\n"


def render(options: list[Option]) -> dict[Path, str]:
    fields = "".join(f"{_doc(o)}  {o.name}?: {TS_TYPES[o.kind]};\n" for o in options)
    return {OUT: HEADER + fields + "}\n"}
