// GENERATED by bindings/codegen/java.py from bindings/options.schema.json.
// Do not edit: change `inkvec::Options` in crates/inkvec, regenerate the schema
// (cargo test -p inkvec), then run `python bindings/codegen/generate.py`.
package com.logolabs.inkvec;

/**
 * Options for one Inkvec trace. Every field is optional and takes its default when missing.
 * Names and meanings are the Rust library's ({@code inkvec::Options}); the tracer checks
 * every value against {@link #toJson()}, and an unknown name is an error rather than a
 * silent no-op.
 *
 * <p>Immutable. Start from {@link #defaults()} or {@link #builder()}; every builder field
 * begins at its Rust default, so setting none of them reproduces {@link #defaults()}.
 */
public final class InkvecOptions {
    private final double precision;
    private final double minArea;
    private final int colors;
    private final double merge;
    private final int maxDim;
    private final double timeBudget;
    private final double margin;
    private final boolean noBackground;
    private final boolean minify;
    private final boolean editability;
    private final boolean nativeAlpha;
    private final boolean cutout;
    private final boolean contentUnits;
    private final boolean harmonize;
    private final double harmonizeThreshold;

    private InkvecOptions(Builder b) {
        this.precision = b.precision;
        this.minArea = b.minArea;
        this.colors = b.colors;
        this.merge = b.merge;
        this.maxDim = b.maxDim;
        this.timeBudget = b.timeBudget;
        this.margin = b.margin;
        this.noBackground = b.noBackground;
        this.minify = b.minify;
        this.editability = b.editability;
        this.nativeAlpha = b.nativeAlpha;
        this.cutout = b.cutout;
        this.contentUnits = b.contentUnits;
        this.harmonize = b.harmonize;
        this.harmonizeThreshold = b.harmonizeThreshold;
    }

    /** Every option at its default -- the command line's defaults. */
    public static InkvecOptions defaults() {
        return new Builder().build();
    }

    /** A builder with every field starting at its default. */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Sets the description-length cost of a coordinate, in pixels: lambda = ln(extent /
     * precision). Smaller values buy more detail with more coordinates. It does not set the digits
     * written; coordinates are always written at 2 decimals.
     *
     * A number &gt; 0.
     *
     * @default 0.1
     */
    public double precision() {
        return precision;
    }

    /**
     * Discard features smaller than this area, in square pixels.
     *
     * A number &gt; 0.
     *
     * @default 2.0
     */
    public double minArea() {
        return minArea;
    }

    /**
     * Maximum palette size.
     *
     * An integer &gt;= 1 and &lt;= 4096.
     *
     * @default 64
     */
    public int colors() {
        return colors;
    }

    /**
     * OKLab distance below which two colours are treated as one ink.
     *
     * A number &gt;= 0.
     *
     * @default 0.035
     */
    public double merge() {
        return merge;
    }

    /**
     * Inputs larger than this on their longer side, in pixels, are traced at this size and the SVG
     * is written at the original size. Trace time grows with the pixel count. 0 means no cap.
     *
     * An integer.
     *
     * @default 2048
     */
    public int maxDim() {
        return maxDim;
    }

    /**
     * Advisory wall-clock budget, in seconds; 0 means none. Gradient-band merging stops at 60% of
     * it and the boundary solve gets 25%; the output is still a correct trace, with more fills or
     * a less polished outline. A nonzero budget makes the output depend on machine speed and load,
     * so it is no longer reproducible.
     *
     * A number &gt;= 0.
     *
     * @default 0.0
     */
    public double timeBudget() {
        return timeBudget;
    }

    /**
     * Transparent margin around the output, as a fraction of the larger side. The viewBox grows;
     * the geometry does not move.
     *
     * A number &gt;= 0.
     *
     * @default 0.0
     */
    public double margin() {
        return margin;
    }

    /**
     * Knock the background out: the face that covers the whole canvas is not painted, so the
     * artwork sits on transparency.
     *
     * @default false
     */
    public boolean noBackground() {
        return noBackground;
    }

    /**
     * No ids or groups, no trailing zeros. Same geometry, typically about a tenth smaller.
     *
     * @default false
     */
    public boolean minify() {
        return minify;
    }

    /**
     * Spend parameters on structure an artist can edit: joins between curves made G1-smooth,
     * handles snapped to the axes and to 45 degrees, handles of one curve made equal in length,
     * nodes that nearly share a coordinate made to share it, and rings that are their own mirror
     * image locked into exact mirrors. Every change is guarded to the fit's own tolerance -- 3
     * sigma of the source point plus half a pixel, or 1.5 px for a mirror lock -- so the picture
     * stays within a fraction of a pixel of the default trace; the price measured on 25 icons is
     * about 0.04 dE00. Off by default.
     *
     * @default false
     */
    public boolean editability() {
        return editability;
    }

    /**
     * Trace transparency natively: each ink is a colour and an opacity, and the transparent ground
     * is an ink of its own, instead of the image being composited onto a matte first. Holes stay
     * holes, white artwork on a transparent ground traces, glows and shadows stay translucent, and
     * a fade is one gradient of colour and opacity. An opaque input traces the same either way. On
     * by default, as on the command line (where the environment variable INKVEC_NATIVE_ALPHA=0
     * turns the default off); false composites onto a matte first, as releases up to 0.1.3 did.
     *
     * @default true
     */
    public boolean nativeAlpha() {
        return nativeAlpha;
    }

    /**
     * With native_alpha off, carry the input's transparency into the SVG: a face the source drew
     * transparent becomes a hole, one drawn at a single opacity keeps it as fill-opacity, and
     * white artwork on a transparent ground survives. Changes nothing for an opaque input, and
     * nothing with native_alpha on (the default), which already carries the transparency out.
     *
     * @default false
     */
    public boolean cutout() {
        return cutout;
    }

    /**
     * Scale the fit tolerances with the raster, so a large, simple drawing gets the parameter
     * count of a small one. Trades fidelity for parsimony: small squares can come back as circles
     * and thin rings broken.
     *
     * @default false
     */
    public boolean contentUnits() {
        return contentUnits;
    }

    /**
     * Shape harmonization (on by default): marks that repeat across the drawing are redrawn from
     * one consensus geometry per cluster, which saves parameters. A mark takes the consensus only
     * where that stays within 0.1 px of the boundary traced for it and costs fewer parameters; a
     * face another face is drawn against, and a fitted circle or rounded rectangle, is never
     * moved. Set it to false to skip the pass.
     *
     * @default true
     */
    public boolean harmonize() {
        return harmonize;
    }

    /**
     * Shape-equivalence threshold for harmonization: the outline similarity (IoU after affine
     * normalisation) above which two marks count as the same shape.
     *
     * A number &gt;= 0 and &lt;= 1.
     *
     * @default 0.92
     */
    public double harmonizeThreshold() {
        return harmonizeThreshold;
    }

    /**
     * The JSON object the C ABI, and every other Inkvec binding, take as options.
     * Every field is written explicitly, so this is equivalent to passing only the
     * fields that differ from {@link #defaults()}.
     */
    public String toJson() {
        StringBuilder sb = new StringBuilder(256);
        sb.append('{');
        sb.append("\"precision\":").append(precision);
        sb.append(",\"min_area\":").append(minArea);
        sb.append(",\"colors\":").append(colors);
        sb.append(",\"merge\":").append(merge);
        sb.append(",\"max_dim\":").append(maxDim);
        sb.append(",\"time_budget\":").append(timeBudget);
        sb.append(",\"margin\":").append(margin);
        sb.append(",\"no_background\":").append(noBackground);
        sb.append(",\"minify\":").append(minify);
        sb.append(",\"editability\":").append(editability);
        sb.append(",\"native_alpha\":").append(nativeAlpha);
        sb.append(",\"cutout\":").append(cutout);
        sb.append(",\"content_units\":").append(contentUnits);
        sb.append(",\"harmonize\":").append(harmonize);
        sb.append(",\"harmonize_threshold\":").append(harmonizeThreshold);
        sb.append('}');
        return sb.toString();
    }

    @Override
    public String toString() {
        return toJson();
    }

    /**
     * Builds an {@link InkvecOptions}. Every field starts at its Rust default; call
     * only the setters you need to change.
     */
    public static final class Builder {
        private double precision = 0.1;
        private double minArea = 2.0;
        private int colors = 64;
        private double merge = 0.035;
        private int maxDim = 2048;
        private double timeBudget = 0.0;
        private double margin = 0.0;
        private boolean noBackground = false;
        private boolean minify = false;
        private boolean editability = false;
        private boolean nativeAlpha = true;
        private boolean cutout = false;
        private boolean contentUnits = false;
        private boolean harmonize = true;
        private double harmonizeThreshold = 0.92;

        private Builder() {
        }

        /**
         * Sets the description-length cost of a coordinate, in pixels: lambda = ln(extent /
         * precision). Smaller values buy more detail with more coordinates. It does not set the digits
         * written; coordinates are always written at 2 decimals.
         *
         * A number &gt; 0.
         *
         * @default 0.1
         */
        public Builder precision(double precision) {
            this.precision = precision;
            return this;
        }

        /**
         * Discard features smaller than this area, in square pixels.
         *
         * A number &gt; 0.
         *
         * @default 2.0
         */
        public Builder minArea(double minArea) {
            this.minArea = minArea;
            return this;
        }

        /**
         * Maximum palette size.
         *
         * An integer &gt;= 1 and &lt;= 4096.
         *
         * @default 64
         */
        public Builder colors(int colors) {
            this.colors = colors;
            return this;
        }

        /**
         * OKLab distance below which two colours are treated as one ink.
         *
         * A number &gt;= 0.
         *
         * @default 0.035
         */
        public Builder merge(double merge) {
            this.merge = merge;
            return this;
        }

        /**
         * Inputs larger than this on their longer side, in pixels, are traced at this size and the SVG
         * is written at the original size. Trace time grows with the pixel count. 0 means no cap.
         *
         * An integer.
         *
         * @default 2048
         */
        public Builder maxDim(int maxDim) {
            this.maxDim = maxDim;
            return this;
        }

        /**
         * Advisory wall-clock budget, in seconds; 0 means none. Gradient-band merging stops at 60% of
         * it and the boundary solve gets 25%; the output is still a correct trace, with more fills or
         * a less polished outline. A nonzero budget makes the output depend on machine speed and load,
         * so it is no longer reproducible.
         *
         * A number &gt;= 0.
         *
         * @default 0.0
         */
        public Builder timeBudget(double timeBudget) {
            this.timeBudget = timeBudget;
            return this;
        }

        /**
         * Transparent margin around the output, as a fraction of the larger side. The viewBox grows;
         * the geometry does not move.
         *
         * A number &gt;= 0.
         *
         * @default 0.0
         */
        public Builder margin(double margin) {
            this.margin = margin;
            return this;
        }

        /**
         * Knock the background out: the face that covers the whole canvas is not painted, so the
         * artwork sits on transparency.
         *
         * @default false
         */
        public Builder noBackground(boolean noBackground) {
            this.noBackground = noBackground;
            return this;
        }

        /**
         * No ids or groups, no trailing zeros. Same geometry, typically about a tenth smaller.
         *
         * @default false
         */
        public Builder minify(boolean minify) {
            this.minify = minify;
            return this;
        }

        /**
         * Spend parameters on structure an artist can edit: joins between curves made G1-smooth,
         * handles snapped to the axes and to 45 degrees, handles of one curve made equal in length,
         * nodes that nearly share a coordinate made to share it, and rings that are their own mirror
         * image locked into exact mirrors. Every change is guarded to the fit's own tolerance -- 3
         * sigma of the source point plus half a pixel, or 1.5 px for a mirror lock -- so the picture
         * stays within a fraction of a pixel of the default trace; the price measured on 25 icons is
         * about 0.04 dE00. Off by default.
         *
         * @default false
         */
        public Builder editability(boolean editability) {
            this.editability = editability;
            return this;
        }

        /**
         * Trace transparency natively: each ink is a colour and an opacity, and the transparent ground
         * is an ink of its own, instead of the image being composited onto a matte first. Holes stay
         * holes, white artwork on a transparent ground traces, glows and shadows stay translucent, and
         * a fade is one gradient of colour and opacity. An opaque input traces the same either way. On
         * by default, as on the command line (where the environment variable INKVEC_NATIVE_ALPHA=0
         * turns the default off); false composites onto a matte first, as releases up to 0.1.3 did.
         *
         * @default true
         */
        public Builder nativeAlpha(boolean nativeAlpha) {
            this.nativeAlpha = nativeAlpha;
            return this;
        }

        /**
         * With native_alpha off, carry the input's transparency into the SVG: a face the source drew
         * transparent becomes a hole, one drawn at a single opacity keeps it as fill-opacity, and
         * white artwork on a transparent ground survives. Changes nothing for an opaque input, and
         * nothing with native_alpha on (the default), which already carries the transparency out.
         *
         * @default false
         */
        public Builder cutout(boolean cutout) {
            this.cutout = cutout;
            return this;
        }

        /**
         * Scale the fit tolerances with the raster, so a large, simple drawing gets the parameter
         * count of a small one. Trades fidelity for parsimony: small squares can come back as circles
         * and thin rings broken.
         *
         * @default false
         */
        public Builder contentUnits(boolean contentUnits) {
            this.contentUnits = contentUnits;
            return this;
        }

        /**
         * Shape harmonization (on by default): marks that repeat across the drawing are redrawn from
         * one consensus geometry per cluster, which saves parameters. A mark takes the consensus only
         * where that stays within 0.1 px of the boundary traced for it and costs fewer parameters; a
         * face another face is drawn against, and a fitted circle or rounded rectangle, is never
         * moved. Set it to false to skip the pass.
         *
         * @default true
         */
        public Builder harmonize(boolean harmonize) {
            this.harmonize = harmonize;
            return this;
        }

        /**
         * Shape-equivalence threshold for harmonization: the outline similarity (IoU after affine
         * normalisation) above which two marks count as the same shape.
         *
         * A number &gt;= 0 and &lt;= 1.
         *
         * @default 0.92
         */
        public Builder harmonizeThreshold(double harmonizeThreshold) {
            this.harmonizeThreshold = harmonizeThreshold;
            return this;
        }

        /** Builds the immutable {@link InkvecOptions}. */
        public InkvecOptions build() {
            return new InkvecOptions(this);
        }
    }
}
