//! Inkvec's HTTP service: the raster-to-SVG facade (`inkvec`) behind axum.
//!
//! One rule holds this crate to the same "one source of truth" discipline as every other
//! binding: it does not know what an option is. `inkvec::Options` is parsed from a JSON
//! object built here purely mechanically -- from a `?options=` query parameter, an
//! `X-Inkvec-Options` header, a multipart `options` part, and generic query parameters typed
//! against `inkvec::options_schema_json()` -- and handed to [`inkvec::Options::from_json`],
//! whose validation errors become the response. No option is named in this file.
//!
//! [`app`] builds the router; [`AppState`] carries the concurrency limiter, body-size cap
//! and optional time budget/timeout read from the environment (see the crate README for the
//! `INKVEC_*` variables). `main.rs` is a thin binary wrapper around this library so the
//! integration tests (`tests/`) can build the same router in-process.

use axum::{
    body::{to_bytes, Body},
    extract::State,
    http::{header, HeaderMap, StatusCode, Uri},
    response::{IntoResponse, Response},
    routing::{get, post},
    Json, Router,
};
use futures_util::TryStreamExt;
use serde_json::{json, Map, Value};
use std::net::SocketAddr;
use std::sync::{Arc, OnceLock};
use std::time::Duration;
use tokio::sync::Semaphore;

/// The generated OpenAPI 3.1 document (`bindings/openapi.json`), served verbatim at
/// `/openapi.json`. Generated by `bindings/codegen/openapi.py` from
/// `bindings/options.schema.json`; `bindings/codegen/generate.py --check` covers it.
pub const OPENAPI_JSON: &str = include_str!("../../../bindings/openapi.json");

/// Default request body limit, in bytes (20 MB), when `INKVEC_MAX_BODY_BYTES` is unset.
pub const DEFAULT_MAX_BODY_BYTES: usize = 20 * 1024 * 1024;

/// Default per-request server-side time cap, in seconds, when `INKVEC_REQUEST_TIMEOUT_SECS`
/// is unset. 0 (via the environment variable) disables the cap.
pub const DEFAULT_REQUEST_TIMEOUT_SECS: u64 = 60;

/// Shared state behind every handler. Cheap to clone: everything is an `Arc` or `Copy`.
#[derive(Clone)]
pub struct AppState {
    /// Bounds how many traces run at once. A request that finds no permit free is rejected
    /// immediately with `503 busy` rather than queued, so load sheds instead of piling up
    /// behind a CPU-bound endpoint.
    semaphore: Arc<Semaphore>,
    /// Maximum accepted request body, in bytes (checked while reading, not just
    /// `Content-Length`, so a chunked or lying body cannot bypass it).
    max_body_bytes: usize,
    /// If set, and the caller's options do not already set `time_budget`, this value is
    /// merged in before validation -- the facade's own advisory budget, applied as a server
    /// default rather than a client requirement. `None` leaves the facade default (no budget).
    default_time_budget: Option<f64>,
    /// If set, the whole trace (decode + pipeline) is capped at this wall-clock duration.
    /// This is a coarse, server-side backstop: dropping the future when it elapses does not
    /// stop the blocking thread running the trace (Rust cannot cancel a running OS thread),
    /// so an abandoned trace keeps consuming a worker thread until it finishes on its own.
    /// See the README's "known limitations".
    request_timeout: Option<Duration>,
    /// Parsed once from `inkvec::options_schema_json()`, used only to type generic query
    /// parameters (`?colors=8` -> the JSON number `8`, `?no_background=true` -> the JSON
    /// bool `true`). The set of recognised keys, and what a value means, come from the
    /// schema; nothing here is named.
    options_schema: Arc<Value>,
}

impl AppState {
    /// Read every `INKVEC_*` configuration variable from the process environment. Never
    /// panics on a bad value; a variable that fails to parse is logged and its default used.
    pub fn from_env() -> Self {
        let cores = std::thread::available_parallelism()
            .map(std::num::NonZeroUsize::get)
            .unwrap_or(1);
        let max_concurrency = env_usize("INKVEC_MAX_CONCURRENCY", cores);
        let max_body_bytes = env_usize("INKVEC_MAX_BODY_BYTES", DEFAULT_MAX_BODY_BYTES);
        let default_time_budget = std::env::var("INKVEC_DEFAULT_TIME_BUDGET")
            .ok()
            .and_then(|s| s.trim().parse::<f64>().ok())
            .filter(|v| v.is_finite() && *v > 0.0);
        let timeout_secs = env_u64("INKVEC_REQUEST_TIMEOUT_SECS", DEFAULT_REQUEST_TIMEOUT_SECS);
        let request_timeout = (timeout_secs > 0).then(|| Duration::from_secs(timeout_secs));
        Self::new(
            max_concurrency,
            max_body_bytes,
            default_time_budget,
            request_timeout,
        )
    }

    /// Construct directly, bypassing the environment: for tests, and for an embedder that
    /// wants to configure the service programmatically instead of through `INKVEC_*`
    /// variables. `max_concurrency` below 1 is treated as 1.
    pub fn new(
        max_concurrency: usize,
        max_body_bytes: usize,
        default_time_budget: Option<f64>,
        request_timeout: Option<Duration>,
    ) -> Self {
        let options_schema: Value =
            serde_json::from_str(inkvec::options_schema_json()).unwrap_or(Value::Null);
        AppState {
            semaphore: Arc::new(Semaphore::new(max_concurrency.max(1))),
            max_body_bytes,
            default_time_budget,
            request_timeout,
            options_schema: Arc::new(options_schema),
        }
    }

    /// The port to bind, from `INKVEC_PORT` (default 8080).
    pub fn port() -> u16 {
        std::env::var("INKVEC_PORT")
            .ok()
            .and_then(|s| s.trim().parse().ok())
            .unwrap_or(8080)
    }

    /// A clone of the concurrency semaphore, for a caller (a test) that wants to hold a
    /// permit itself to deterministically exercise the `503 busy` path without a timing
    /// race against real trace latency.
    pub fn concurrency_semaphore(&self) -> Arc<Semaphore> {
        self.semaphore.clone()
    }
}

fn env_usize(name: &str, default: usize) -> usize {
    std::env::var(name)
        .ok()
        .and_then(|s| s.trim().parse().ok())
        .unwrap_or(default)
}

fn env_u64(name: &str, default: u64) -> u64 {
    std::env::var(name)
        .ok()
        .and_then(|s| s.trim().parse().ok())
        .unwrap_or(default)
}

/// The router: every endpoint in the README's table, wired to `state`.
pub fn app(state: AppState) -> Router {
    Router::new()
        .route("/trace", post(trace))
        .route("/options/schema", get(options_schema))
        .route("/options/defaults", get(options_defaults))
        .route("/healthz", get(healthz))
        .route("/version", get(version))
        .route("/openapi.json", get(openapi))
        .with_state(state)
}

// ---------------------------------------------------------------------------------------
// Simple endpoints
// ---------------------------------------------------------------------------------------

async fn healthz() -> impl IntoResponse {
    (StatusCode::OK, Json(json!({ "status": "ok" })))
}

async fn version() -> impl IntoResponse {
    Json(json!({
        "version": inkvec::version(),
        "build_target": inkvec::build_target(),
    }))
}

async fn options_schema() -> impl IntoResponse {
    (
        [(header::CONTENT_TYPE, "application/json")],
        inkvec::options_schema_json(),
    )
}

async fn options_defaults() -> impl IntoResponse {
    Json(serde_json::to_value(inkvec::Options::default()).unwrap_or(Value::Null))
}

async fn openapi() -> impl IntoResponse {
    ([(header::CONTENT_TYPE, "application/json")], OPENAPI_JSON)
}

// ---------------------------------------------------------------------------------------
// POST /trace
// ---------------------------------------------------------------------------------------

async fn trace(
    State(state): State<AppState>,
    headers: HeaderMap,
    uri: Uri,
    body: Body,
) -> Response {
    match trace_inner(state, headers, uri, body).await {
        Ok(resp) => resp,
        Err(e) => e.into_response(),
    }
}

async fn trace_inner(
    state: AppState,
    headers: HeaderMap,
    uri: Uri,
    body: Body,
) -> Result<Response, ApiError> {
    // Shed load rather than queue: a CPU-bound endpoint that queued would just move the
    // wait from the network into memory.
    let _permit = state
        .semaphore
        .clone()
        .try_acquire_owned()
        .map_err(|_| ApiError::Busy)?;

    let content_type = headers
        .get(header::CONTENT_TYPE)
        .and_then(|v| v.to_str().ok())
        .unwrap_or("")
        .to_string();

    let query_pairs: Vec<(String, String)> = uri
        .query()
        .map(|q| form_urlencoded::parse(q.as_bytes()).into_owned().collect())
        .unwrap_or_default();

    let (image, options_from_body) = if content_type_is(&content_type, "multipart/form-data") {
        read_multipart(body, &content_type, state.max_body_bytes).await?
    } else {
        let bytes = to_bytes(body, state.max_body_bytes).await.map_err(|_| {
            ApiError::TooLarge(format!("body exceeds {} bytes", state.max_body_bytes))
        })?;
        (bytes.to_vec(), None)
    };

    if image.is_empty() {
        return Err(ApiError::InvalidImage(
            "no image bytes in the request".into(),
        ));
    }

    let merged = merge_options(&state, &query_pairs, &headers, options_from_body.as_deref())?;
    let mut opts = inkvec::Options::from_json(&merged.to_string()).map_err(ApiError::from)?;
    if let Some(budget) = state.default_time_budget {
        if merged.get("time_budget").is_none() {
            opts.time_budget = budget;
        }
    }

    let traced = run_trace(image, opts, state.request_timeout).await?;

    let mut response = Response::builder()
        .status(StatusCode::OK)
        .header(header::CONTENT_TYPE, "image/svg+xml")
        .header("X-Inkvec-Width", traced.width)
        .header("X-Inkvec-Height", traced.height)
        .body(Body::from(traced.svg))
        .unwrap_or_else(|_| StatusCode::INTERNAL_SERVER_ERROR.into_response());
    response.headers_mut().insert(
        header::CACHE_CONTROL,
        header::HeaderValue::from_static("no-store"),
    );
    Ok(response)
}

/// Run the trace on the blocking pool, under an optional wall-clock cap.
///
/// The cap is a backstop, not a cancellation: dropping the timed-out future stops *waiting*
/// for the blocking task, but the task itself (already handed to the blocking pool) keeps
/// running to completion or panic, since Rust has no way to interrupt a running OS thread.
/// See `AppState::request_timeout` and the README.
async fn run_trace(
    image: Vec<u8>,
    opts: inkvec::Options,
    timeout: Option<Duration>,
) -> Result<inkvec::Traced, ApiError> {
    let work = tokio::task::spawn_blocking(move || inkvec::trace(&image, &opts));
    let joined = match timeout {
        Some(d) => tokio::time::timeout(d, work).await.map_err(|_| {
            ApiError::Internal(format!(
                "trace exceeded the server's request timeout of {:.1}s; time_budget is advisory \
                 and cannot guarantee this on its own",
                d.as_secs_f64()
            ))
        })?,
        None => work.await,
    };
    let result = joined.map_err(|e| ApiError::Internal(format!("the trace task panicked: {e}")))?;
    result.map_err(ApiError::from)
}

/// Read a `multipart/form-data` body: the `image` part's bytes and, if present, the
/// `options` part's text (unparsed JSON, merged in by [`merge_options`]).
async fn read_multipart(
    body: Body,
    content_type: &str,
    max_body_bytes: usize,
) -> Result<(Vec<u8>, Option<String>), ApiError> {
    let boundary = multer::parse_boundary(content_type)
        .map_err(|e| ApiError::InvalidImage(format!("bad multipart boundary: {e}")))?;
    let stream = body.into_data_stream().map_err(std::io::Error::other);
    let constraints = multer::Constraints::new()
        .size_limit(multer::SizeLimit::new().whole_stream(max_body_bytes as u64));
    let mut multipart = multer::Multipart::with_constraints(stream, boundary, constraints);

    let mut image: Option<Vec<u8>> = None;
    let mut options: Option<String> = None;
    loop {
        let field = multipart.next_field().await.map_err(map_multer_error)?;
        let Some(field) = field else { break };
        match field.name().unwrap_or("") {
            "image" => {
                let bytes = field.bytes().await.map_err(map_multer_error)?;
                image = Some(bytes.to_vec());
            }
            "options" => {
                let text = field.text().await.map_err(map_multer_error)?;
                options = Some(text);
            }
            _ => {
                // An unrecognised part is ignored rather than rejected: this endpoint has
                // exactly two named parts, and a client sending an extra one (a filename
                // field from a browser form, say) should not fail the request.
            }
        }
    }
    let image =
        image.ok_or_else(|| ApiError::InvalidImage("multipart body has no `image` part".into()))?;
    Ok((image, options))
}

fn map_multer_error(e: multer::Error) -> ApiError {
    if matches!(
        e,
        multer::Error::StreamSizeExceeded { .. } | multer::Error::FieldSizeExceeded { .. }
    ) {
        ApiError::TooLarge(e.to_string())
    } else {
        ApiError::InvalidImage(format!("bad multipart body: {e}"))
    }
}

fn content_type_is(content_type: &str, wanted: &str) -> bool {
    content_type
        .split(';')
        .next()
        .unwrap_or("")
        .trim()
        .eq_ignore_ascii_case(wanted)
}

// ---------------------------------------------------------------------------------------
// Options: query params, header, and the multipart JSON part merged, schema-typed, then
// handed to inkvec::Options::from_json for the one real validation pass.
// ---------------------------------------------------------------------------------------

/// Build the JSON object passed to [`inkvec::Options::from_json`], from lowest to highest
/// priority: generic query parameters typed against the schema, then `?options=`, then
/// `X-Inkvec-Options`, then (for multipart requests) the `options` part. A later source
/// overrides a key an earlier one set; nothing here is validated beyond typing a query
/// parameter's string against the schema's declared type -- range and unknown-key checks are
/// the facade's, in `Options::from_json`.
fn merge_options(
    state: &AppState,
    query_pairs: &[(String, String)],
    headers: &HeaderMap,
    body_options: Option<&str>,
) -> Result<Value, ApiError> {
    let mut merged = Map::new();

    let generic = typed_query_options(&state.options_schema, query_pairs)?;
    merge_into(&mut merged, generic);

    if let Some((_, raw)) = query_pairs.iter().find(|(k, _)| k == "options") {
        merge_into(
            &mut merged,
            parse_options_object(raw, "the `options` query parameter")?,
        );
    }

    if let Some(raw) = headers
        .get("X-Inkvec-Options")
        .and_then(|v| v.to_str().ok())
    {
        merge_into(
            &mut merged,
            parse_options_object(raw, "the X-Inkvec-Options header")?,
        );
    }

    if let Some(raw) = body_options {
        merge_into(
            &mut merged,
            parse_options_object(raw, "the multipart `options` part")?,
        );
    }

    Ok(Value::Object(merged))
}

fn merge_into(target: &mut Map<String, Value>, source: Map<String, Value>) {
    for (k, v) in source {
        target.insert(k, v);
    }
}

fn parse_options_object(raw: &str, from: &str) -> Result<Map<String, Value>, ApiError> {
    let raw = raw.trim();
    if raw.is_empty() {
        return Ok(Map::new());
    }
    match serde_json::from_str::<Value>(raw) {
        Ok(Value::Object(m)) => Ok(m),
        Ok(_) => Err(ApiError::InvalidOptions(format!(
            "{from} must be a JSON object"
        ))),
        Err(e) => Err(ApiError::InvalidOptions(format!(
            "{from} is not valid JSON: {e}"
        ))),
    }
}

/// Query parameters whose key is a property of the options schema, converted to that
/// property's JSON type (`boolean`, `integer`, `number` or `string`). A key the schema does not have is
/// left for `Options::from_json` to reject (or, for `options`, is not an option at all and is
/// skipped here). A value that does not parse as its schema type is `invalid_options` naming
/// the key, the same shape of error the facade itself returns.
fn typed_query_options(
    schema: &Value,
    query_pairs: &[(String, String)],
) -> Result<Map<String, Value>, ApiError> {
    let properties = schema.get("properties").and_then(Value::as_object);
    let mut out = Map::new();
    let Some(properties) = properties else {
        return Ok(out);
    };
    for (key, raw) in query_pairs {
        if key == "options" {
            continue;
        }
        let Some(prop) = properties.get(key) else {
            continue; // not an option; Options::from_json will reject it if it is meant as one
        };
        let kind = prop.get("type").and_then(Value::as_str).unwrap_or("");
        let value = match kind {
            "boolean" => parse_query_bool(key, raw)?,
            "integer" | "number" => raw
                .trim()
                .parse::<f64>()
                .ok()
                .filter(|v| v.is_finite())
                .map(|v| json_number(v, kind == "integer"))
                .ok_or_else(|| {
                    ApiError::InvalidOptions(format!("`{key}` must be a {kind}, got {raw:?}"))
                })?,
            // Taken as written; `Options::from_json` validates what it means.
            "string" => Value::String(raw.clone()),
            _ => continue,
        };
        out.insert(key.clone(), value);
    }
    Ok(out)
}

fn parse_query_bool(key: &str, raw: &str) -> Result<Value, ApiError> {
    match raw.trim().to_ascii_lowercase().as_str() {
        "true" | "1" => Ok(Value::Bool(true)),
        "false" | "0" => Ok(Value::Bool(false)),
        _ => Err(ApiError::InvalidOptions(format!(
            "`{key}` must be a bool (true/false/1/0), got {raw:?}"
        ))),
    }
}

fn json_number(v: f64, as_integer: bool) -> Value {
    if as_integer && v.fract() == 0.0 && v >= 0.0 && v <= u64::MAX as f64 {
        Value::from(v as u64)
    } else {
        serde_json::Number::from_f64(v)
            .map(Value::Number)
            .unwrap_or(Value::Null)
    }
}

// ---------------------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------------------

/// The service's own error kinds, one more (`too_large`, `busy`) than the facade's
/// [`inkvec::Error`] -- both bodies as `{ "error": { "code": ..., "message": ... } }`.
#[derive(Debug)]
enum ApiError {
    InvalidImage(String),
    InvalidOptions(String),
    Internal(String),
    TooLarge(String),
    Busy,
}

impl ApiError {
    fn code(&self) -> &'static str {
        match self {
            ApiError::InvalidImage(_) => "invalid_image",
            ApiError::InvalidOptions(_) => "invalid_options",
            ApiError::Internal(_) => "internal",
            ApiError::TooLarge(_) => "too_large",
            ApiError::Busy => "busy",
        }
    }

    fn status(&self) -> StatusCode {
        match self {
            ApiError::InvalidImage(_) => StatusCode::BAD_REQUEST,
            ApiError::InvalidOptions(_) => StatusCode::UNPROCESSABLE_ENTITY,
            ApiError::Internal(_) => StatusCode::INTERNAL_SERVER_ERROR,
            ApiError::TooLarge(_) => StatusCode::PAYLOAD_TOO_LARGE,
            ApiError::Busy => StatusCode::SERVICE_UNAVAILABLE,
        }
    }

    fn message(&self) -> String {
        match self {
            ApiError::InvalidImage(m)
            | ApiError::InvalidOptions(m)
            | ApiError::Internal(m)
            | ApiError::TooLarge(m) => m.clone(),
            ApiError::Busy => "the server is at its concurrency limit; try again shortly".into(),
        }
    }
}

impl From<inkvec::Error> for ApiError {
    fn from(e: inkvec::Error) -> Self {
        let message = e.message().to_string();
        match e.code() {
            "invalid_image" => ApiError::InvalidImage(message),
            "invalid_options" => ApiError::InvalidOptions(message),
            _ => ApiError::Internal(message),
        }
    }
}

impl IntoResponse for ApiError {
    fn into_response(self) -> Response {
        if matches!(self, ApiError::Internal(_)) {
            tracing::error!(message = %self.message(), "internal error");
        }
        let status = self.status();
        let body = json!({ "error": { "code": self.code(), "message": self.message() } });
        (status, Json(body)).into_response()
    }
}

// ---------------------------------------------------------------------------------------
// The `--healthcheck` CLI mode (main.rs), for a distroless image with no shell/curl.
// ---------------------------------------------------------------------------------------

/// Connect to `127.0.0.1:<INKVEC_PORT>/healthz` with a short timeout and check for a `200`
/// status line. Blocking, by design: this runs as `inkvec-server --healthcheck` from Docker's
/// `HEALTHCHECK`, a separate short-lived process with nothing else to do.
pub fn healthcheck() -> i32 {
    use std::io::{Read, Write};
    use std::net::TcpStream;

    let port = AppState::port();
    let addr = format!("127.0.0.1:{port}");
    let deadline = Duration::from_secs(3);
    let mut stream = match TcpStream::connect_timeout(
        &addr
            .parse()
            .unwrap_or_else(|_| SocketAddr::from(([127, 0, 0, 1], port))),
        deadline,
    ) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("inkvec-server --healthcheck: connect to {addr} failed: {e}");
            return 1;
        }
    };
    let _ = stream.set_read_timeout(Some(deadline));
    let _ = stream.set_write_timeout(Some(deadline));
    let request =
        format!("GET /healthz HTTP/1.0\r\nHost: 127.0.0.1:{port}\r\nConnection: close\r\n\r\n");
    if let Err(e) = stream.write_all(request.as_bytes()) {
        eprintln!("inkvec-server --healthcheck: write failed: {e}");
        return 1;
    }
    let mut response = String::new();
    if let Err(e) = stream.read_to_string(&mut response) {
        // A short read after the headers is fine; only a failed read before any status
        // line is fatal. `read_to_string` fails immediately on invalid UTF-8, which the
        // status line never is, so treat any error here as a failure to be safe.
        eprintln!("inkvec-server --healthcheck: read failed: {e}");
        return 1;
    }
    if response.starts_with("HTTP/1.0 200") || response.starts_with("HTTP/1.1 200") {
        0
    } else {
        eprintln!(
            "inkvec-server --healthcheck: unhealthy response: {}",
            response.lines().next().unwrap_or("")
        );
        1
    }
}

static INIT_LOGGING: OnceLock<()> = OnceLock::new();

/// Install the `tracing` subscriber once (idempotent, so tests that call it repeatedly are
/// safe). Reads `RUST_LOG`, defaulting to `info`.
pub fn init_logging() {
    INIT_LOGGING.get_or_init(|| {
        use tracing_subscriber::{fmt, EnvFilter};
        let filter = EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("info"));
        let _ = fmt().with_env_filter(filter).try_init();
    });
}

// ---------------------------------------------------------------------------------------
// Unit tests for the pure pieces: option merging and typing, and error mapping. The HTTP
// surface itself (every endpoint, all body and option-source kinds, error status codes, the
// concurrency limit) is covered by the integration tests in `tests/`, which need a real
// router; these are the parts small enough, and easy enough to get subtly wrong, to pin down
// without one.
// ---------------------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn test_schema() -> Value {
        json!({
            "properties": {
                "colors": {"type": "integer"},
                "merge": {"type": "number"},
                "no_background": {"type": "boolean"},
                "merge_colors": {"type": "string"},
            }
        })
    }

    #[test]
    fn content_type_is_ignores_parameters_and_case() {
        assert!(content_type_is(
            "multipart/form-data; boundary=x",
            "multipart/form-data"
        ));
        assert!(content_type_is(
            "MULTIPART/FORM-DATA",
            "multipart/form-data"
        ));
        assert!(content_type_is(
            " multipart/form-data ",
            "multipart/form-data"
        ));
        assert!(!content_type_is("application/json", "multipart/form-data"));
        assert!(!content_type_is("", "multipart/form-data"));
    }

    #[test]
    fn typed_query_options_converts_by_schema_type_and_ignores_unknown_keys() {
        let schema = test_schema();
        let pairs = vec![
            ("colors".to_string(), "8".to_string()),
            ("merge".to_string(), "0.5".to_string()),
            ("no_background".to_string(), "true".to_string()),
            ("merge_colors".to_string(), "#f00>#00f,#0a0=@1".to_string()),
            ("options".to_string(), "{}".to_string()), // handled elsewhere, must be skipped
            ("not_an_option".to_string(), "whatever".to_string()),
        ];
        let out = typed_query_options(&schema, &pairs).expect("valid");
        assert_eq!(out.get("colors"), Some(&Value::from(8u64)));
        assert_eq!(out.get("merge"), Some(&Value::from(0.5)));
        assert_eq!(out.get("no_background"), Some(&Value::Bool(true)));
        assert_eq!(
            out.get("merge_colors"),
            Some(&Value::from("#f00>#00f,#0a0=@1"))
        );
        assert!(!out.contains_key("options"));
        assert!(!out.contains_key("not_an_option"));
    }

    #[test]
    fn typed_query_options_rejects_a_value_that_does_not_match_its_type() {
        let schema = test_schema();
        let pairs = vec![("colors".to_string(), "not-a-number".to_string())];
        let err = typed_query_options(&schema, &pairs).unwrap_err();
        assert_eq!(err.code(), "invalid_options");
        assert!(err.message().contains("colors"));
    }

    #[test]
    fn parse_query_bool_accepts_true_false_1_0_case_insensitively() {
        assert_eq!(parse_query_bool("x", "true").unwrap(), Value::Bool(true));
        assert_eq!(parse_query_bool("x", "TRUE").unwrap(), Value::Bool(true));
        assert_eq!(parse_query_bool("x", "1").unwrap(), Value::Bool(true));
        assert_eq!(parse_query_bool("x", "false").unwrap(), Value::Bool(false));
        assert_eq!(parse_query_bool("x", "0").unwrap(), Value::Bool(false));
        assert!(parse_query_bool("x", "yes").is_err());
    }

    #[test]
    fn json_number_prefers_an_integer_json_value_for_a_whole_integer_typed_field() {
        assert_eq!(json_number(8.0, true), Value::from(8u64));
        assert_eq!(json_number(0.5, false), Value::from(0.5));
        // Not a whole number: falls back to a JSON number even though `as_integer` was asked.
        assert_eq!(json_number(1.5, true), Value::from(1.5));
    }

    #[test]
    fn merge_into_lets_a_later_source_override_an_earlier_ones_key() {
        let mut target = Map::new();
        target.insert("colors".into(), Value::from(2));
        target.insert("minify".into(), Value::Bool(false));
        let mut source = Map::new();
        source.insert("colors".into(), Value::from(8));
        merge_into(&mut target, source);
        assert_eq!(target.get("colors"), Some(&Value::from(8)));
        assert_eq!(target.get("minify"), Some(&Value::Bool(false)));
    }

    #[test]
    fn parse_options_object_requires_a_json_object() {
        assert!(parse_options_object("", "x").unwrap().is_empty());
        assert!(parse_options_object("  ", "x").unwrap().is_empty());
        assert!(parse_options_object(r#"{"colors":8}"#, "x")
            .unwrap()
            .contains_key("colors"));
        assert!(parse_options_object("[1,2]", "x").is_err());
        assert!(parse_options_object("not json", "x").is_err());
    }

    #[test]
    fn api_error_code_and_status_agree_with_the_readme_s_table() {
        let cases: Vec<(ApiError, &str, StatusCode)> = vec![
            (
                ApiError::InvalidImage("m".into()),
                "invalid_image",
                StatusCode::BAD_REQUEST,
            ),
            (
                ApiError::InvalidOptions("m".into()),
                "invalid_options",
                StatusCode::UNPROCESSABLE_ENTITY,
            ),
            (
                ApiError::Internal("m".into()),
                "internal",
                StatusCode::INTERNAL_SERVER_ERROR,
            ),
            (
                ApiError::TooLarge("m".into()),
                "too_large",
                StatusCode::PAYLOAD_TOO_LARGE,
            ),
            (ApiError::Busy, "busy", StatusCode::SERVICE_UNAVAILABLE),
        ];
        for (err, code, status) in cases {
            assert_eq!(err.code(), code);
            assert_eq!(err.status(), status);
        }
    }

    #[test]
    fn inkvec_error_maps_to_the_matching_api_error() {
        let invalid_image: ApiError = inkvec::Error::InvalidImage("bad".into()).into();
        assert_eq!(invalid_image.code(), "invalid_image");
        let invalid_options: ApiError = inkvec::Error::InvalidOptions("bad".into()).into();
        assert_eq!(invalid_options.code(), "invalid_options");
        let internal: ApiError = inkvec::Error::Internal("bad".into()).into();
        assert_eq!(internal.code(), "internal");
    }

    #[test]
    fn app_state_new_clamps_max_concurrency_to_at_least_one() {
        let state = AppState::new(0, 1024, None, None);
        assert_eq!(state.concurrency_semaphore().available_permits(), 1);
    }
}
