// GENERATED by bindings/codegen/typescript.py from bindings/options.schema.json.
// Do not edit: change `inkvec::Options` in crates/inkvec, regenerate the schema
// (cargo test -p inkvec), then run `python bindings/codegen/generate.py`.

/**
 * Options for one trace. Every field is optional and takes its default when missing.
 * Names and meanings are the Rust library's (`inkvec::Options`); the tracer checks every
 * value, and an unknown name is an error rather than a silent no-op.
 */
export interface Options {
  /**
   * Sets the description-length cost of a coordinate, in pixels: lambda = ln(extent /
   * precision). Smaller values buy more detail with more coordinates. It does not set the
   * digits written; coordinates are always written at 2 decimals.
   *
   * A number > 0.
   *
   * @default 0.1
   */
  precision?: number;
  /**
   * Discard features smaller than this area, in square pixels.
   *
   * A number > 0.
   *
   * @default 2.0
   */
  min_area?: number;
  /**
   * Maximum palette size.
   *
   * An integer >= 1 and <= 4096.
   *
   * @default 64
   */
  colors?: number;
  /**
   * OKLab distance below which two colours are treated as one ink.
   *
   * A number >= 0.
   *
   * @default 0.035
   */
  merge?: number;
  /**
   * Inputs larger than this on their longer side, in pixels, are traced at this size and
   * the SVG is written at the original size. Trace time grows with the pixel count. 0
   * means no cap.
   *
   * An integer.
   *
   * @default 2048
   */
  max_dim?: number;
  /**
   * Advisory wall-clock budget, in seconds; 0 means none. Gradient-band merging stops at
   * 60% of it and the boundary solve gets 25%; the output is still a correct trace, with
   * more fills or a less polished outline. A nonzero budget makes the output depend on
   * machine speed and load, so it is no longer reproducible.
   *
   * A number >= 0.
   *
   * @default 0.0
   */
  time_budget?: number;
  /**
   * Transparent margin around the output, as a fraction of the larger side. The viewBox
   * grows; the geometry does not move.
   *
   * A number >= 0.
   *
   * @default 0.0
   */
  margin?: number;
  /**
   * Knock the background out: the face that covers the whole canvas is not painted, so the
   * artwork sits on transparency.
   *
   * @default false
   */
  no_background?: boolean;
  /**
   * No ids or groups, no trailing zeros. Same geometry, typically about a tenth smaller.
   *
   * @default false
   */
  minify?: boolean;
  /**
   * Carry the input's transparency into the SVG: a face the source drew transparent
   * becomes a hole, one drawn at a single opacity keeps it as fill-opacity, and white
   * artwork on a transparent ground survives. Changes nothing for an opaque input. Off by
   * default because over white it opens faint seams along shared edges; use it for artwork
   * that will sit on anything but white.
   *
   * @default false
   */
  cutout?: boolean;
  /**
   * Scale the fit tolerances with the raster, so a large, simple drawing gets the
   * parameter count of a small one. Trades fidelity for parsimony: small squares can come
   * back as circles and thin rings broken.
   *
   * @default false
   */
  content_units?: boolean;
  /**
   * Shape harmonization (on by default): marks that repeat across the drawing are redrawn
   * from one consensus geometry per cluster, which saves parameters. The known cost is
   * fidelity on fine-line art: on hairlines, thin rings and small rounded details the
   * consensus can displace thin lines by about a pixel (on the 246-icon screen set mean
   * dE00 0.151 off vs 0.299 on). Set it to false for such artwork.
   *
   * @default true
   */
  harmonize?: boolean;
  /**
   * Shape-equivalence threshold for harmonization: the outline similarity (IoU after
   * affine normalisation) above which two marks count as the same shape.
   *
   * A number >= 0 and <= 1.
   *
   * @default 0.92
   */
  harmonize_threshold?: number;
}
