"""Regenerate docs/THIRD_PARTY.md from the resolved dependency graph.

    python tools/third_party.py            # write docs/THIRD_PARTY.md
    python tools/third_party.py --check    # exit 1 if the file is out of date

Three builds are resolved with `cargo tree`: the default workspace build, the build with the
ONNX Runtime restorer (`inkvec-cli/restore-model`), and every feature. `cargo tree` is used rather
than `cargo metadata` because it resolves features the way a real build does: `cargo metadata`
keeps optional dependencies that no feature combination of ours enables (for example Burn's
training UI, `burn-train` -> `ratatui` -> `termwiz` -> `terminfo`), which would list licences we
never compile. Dev-only dependencies are left out; build-script dependencies are included.

Each crate is listed with its declared licence and the smallest of those builds that compiles
it. The non-crate sections (Python tools, native runtimes, benchmark data) are kept in this file
so a regeneration cannot drop them.
"""

from __future__ import annotations

import datetime
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "THIRD_PARTY.md"
CARGO = shutil.which("cargo") or str(Path.home() / ".cargo" / "bin" / "cargo")

PERMISSIVE = {
    "MIT", "MIT-0", "Apache-2.0", "BSD-2-Clause", "BSD-3-Clause", "ISC", "Zlib", "0BSD",
    "Unicode-3.0", "Unicode-DFS-2016", "Unlicense", "CC0-1.0", "BSL-1.0", "Apache-2.0 WITH LLVM-exception",
    "CDLA-Permissive-2.0",
}

BUILDS = [
    ("default", ["--workspace"]),
    ("restore-model", ["--workspace", "--features", "inkvec-cli/restore-model"]),
    ("all features", ["--workspace", "--all-features"]),
]

HEADER = """# Third-party components

Generated by `tools/third_party.py` on {date}. Regenerate it after changing dependencies.
Inkvec itself is licensed under Apache-2.0 (`LICENSE`).

{summary}

## Python tools and model weights

| component | licence | notes |
|---|---|---|
| MambaIR / MambaIRv2 (SR pre-pass architecture and released weights) | Apache-2.0 | https://github.com/csguoh/MambaIR; weights are downloaded by `tools/inkvec_sr`, not redistributed here |
| mamba-ssm | Apache-2.0 | https://github.com/state-spaces/mamba |
| PyTorch (Python tool path only) | BSD-3-Clause | not shipped with the binary |

The benchmark harness (`bench/`) uses `tqdm` (MPL-2.0 AND MIT) and, through `requests`, `certifi`
(MPL-2.0). Neither is shipped with Inkvec.

## Native runtimes for the restorer (optional)

| component | licence | notes |
|---|---|---|
| ONNX Runtime (`restore-model`) | MIT | the binary bundles third-party code, including Eigen (MPL-2.0); ship Microsoft's `ThirdPartyNotices.txt` with any redistributed `onnxruntime` library |
| DirectML (`DirectML.dll`) | Microsoft DirectML License Agreement (proprietary) | only in the prebuilt static Windows package `ort` downloads; not needed for CPU inference and not part of a build linked against Microsoft's CPU release. Review its terms before redistributing it |

## Benchmark corpus (`bench/data`)

The screen-set rasters committed under `bench/data` are renders of third-party icon sets. They
are test data, not part of any build. Each keeps its upstream licence:

| family | licence | attribution | notes |
|---|---|---|---|
| lucide | ISC (includes Feather's MIT notice) | yes | https://github.com/lucide-icons/lucide |
| material-icons | Apache-2.0 | notice | https://github.com/google/material-design-icons |
| simple-icons | CC0-1.0 | no | brand logos: the marks remain trademarks of their owners; see simple-icons `DISCLAIMER.md` |
| twemoji | CC-BY 4.0 (graphics) | yes | https://github.com/jdecked/twemoji |
| noto-emoji | Apache-2.0 (images), OFL-1.1 (fonts) | notice | https://github.com/googlefonts/noto-emoji |
| openmoji | CC-BY-SA 4.0 | yes, share-alike | https://openmoji.org |
| synthetic | generated by this project | no | `bench/cases` |

Licence review notes for these families: `docs/legal/`.

## Rust crates ({count})

`builds` is the smallest build that compiles the crate: `default` (every workspace build),
`restore-model` (only with the ONNX Runtime restorer), or `all features` (only with an optional
feature such as the Burn restorer backends). Build-script dependencies are included, so a crate
listed here is compiled but not necessarily linked into the binary.

| crate | version | licence | builds |
|---|---|---|---|
"""

ANSI_ESCAPE = re.compile(r"\x1b\[[0-9;]*[a-zA-Z]")
LINE = re.compile(r"^(?P<name>[A-Za-z0-9_.-]+) v(?P<version>\S+)(?: \((?P<src>[^)]*)\))?(?: \(\*\))?\|(?P<lic>.*)$")


def tree(extra: list[str]) -> dict[tuple[str, str], str | None]:
    """Crates compiled by one build, as (name, version) -> declared licence."""
    r = subprocess.run(
        [CARGO, "tree", *extra, "--color", "never", "-e", "normal,build", "--target", "all", "--prefix", "none", "--format", "{p}|{l}"],
        cwd=ROOT, capture_output=True, text=True, encoding="utf-8", errors="replace",
    )
    if r.returncode != 0:
        sys.exit(f"cargo tree {' '.join(extra)} failed:\n{r.stderr[-2000:]}")
    out: dict[tuple[str, str], str | None] = {}
    for line in r.stdout.splitlines():
        clean = ANSI_ESCAPE.sub("", line.strip())
        m = LINE.match(clean)
        if not m:
            continue
        src = m.group("src") or ""
        if src and not src.startswith("http") and ("\\" in src or "/" in src or ":" in src):
            continue  # a workspace member (path source)
        # `cargo tree` appends " (*)" after the whole formatted line for a crate it already printed.
        lic = ANSI_ESCAPE.sub("", m.group("lic"))
        lic = re.sub(r"\s*\(\*\)\s*$", "", lic).strip()
        out[(m.group("name"), m.group("version"))] = lic or None
    return out


def permissive(expr: str | None) -> bool:
    if not expr:
        return False
    expr = expr.replace("/", " OR ")
    for alt in re.split(r"\s+OR\s+", expr.replace("(", " ").replace(")", " ")):
        terms = [t.strip() for t in re.split(r"\s+AND\s+", alt) if t.strip()]
        if terms and all(t in PERMISSIVE for t in terms):
            return True
    return False


def render() -> str:
    first: dict[tuple[str, str], tuple[str, str | None]] = {}
    for name, args in BUILDS:
        for key, lic in tree(args).items():
            first.setdefault(key, (name, lic))
    rows = sorted(first.items())
    flagged = [(n, v, lic, b) for (n, v), (b, lic) in rows if not permissive(lic)]
    counts = {name: sum(1 for (_, (b, _)) in rows if b == name) for name, _ in BUILDS}
    lines = [
        f"{len(rows)} Rust crates are compiled across all builds: {counts['default']} in every build, "
        f"{counts['restore-model']} more with the ONNX Runtime restorer, {counts['all features']} more only with other optional features.",
    ]
    if flagged:
        lines += ["", "Not under a permissive licence (or no licence declared), with the smallest build that compiles them:", ""]
        lines += [f"- `{n}` {v}: {lic or 'no licence declared'} ({b})" for n, v, lic, b in flagged]
    else:
        lines.append("Every one is under a permissive licence or offers one as a choice.")
    text = HEADER.format(date=datetime.date.today().isoformat(), summary="\n".join(lines), count=len(rows))
    text += "\n".join(f"| {n} | {v} | {lic or 'none declared'} | {b} |" for (n, v), (b, lic) in rows) + "\n"
    return text


def main() -> int:
    text = render()
    if "--check" in sys.argv:
        old = OUT.read_text("utf-8") if OUT.exists() else ""
        strip = lambda s: re.sub(r"on \d{4}-\d{2}-\d{2}\.", "", s)
        s_old = strip(old).replace("\r\n", "\n")
        s_text = strip(text).replace("\r\n", "\n")
        if s_old != s_text:
            import difflib
            print("docs/THIRD_PARTY.md is out of date; diff follows:")
            for line in difflib.unified_diff(
                s_old.splitlines(), s_text.splitlines(), fromfile="committed", tofile="rendered"
            ):
                print(line)
            print("docs/THIRD_PARTY.md is out of date; run python tools/third_party.py")
            return 1
        return 0
    OUT.write_text(text, "utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
