// GENERATED by bindings/codegen/swift.py from bindings/options.schema.json.
// Do not edit: change `inkvec::Options` in crates/inkvec, regenerate the schema
// (cargo test -p inkvec), then run `python bindings/codegen/generate.py`.

/// Options for one trace.
///
/// Every property is optional. `nil` leaves the option out of the JSON the tracer receives,
/// so it takes the Rust library's default (`Inkvec.defaults` reads them all). Names and
/// meanings are `inkvec::Options`'s; the tracer checks every value, and a value of the wrong
/// type or out of range is an `InkvecError.invalidOptions` that names the option.
///
/// ```swift
/// var options = InkvecOptions(colors: 16)
/// options.noBackground = true
/// let traced = try Inkvec.trace(png, options: options)
/// ```
public struct InkvecOptions: Codable, Hashable, Sendable {
    /// Sets the description-length cost of a coordinate, in pixels: lambda = ln(extent /
    /// precision). Smaller values buy more detail with more coordinates. It does not set the
    /// digits written; coordinates are always written at 2 decimals.
    ///
    /// A number > 0. Default: `0.1`.
    public var precision: Double?

    /// Discard features smaller than this area, in square pixels.
    ///
    /// A number > 0. Default: `2.0`.
    public var minArea: Double?

    /// Maximum palette size.
    ///
    /// An integer >= 1 and <= 4096. Default: `64`.
    public var colors: Int?

    /// OKLab distance below which two colours are treated as one ink.
    ///
    /// A number >= 0. Default: `0.035`.
    public var merge: Double?

    /// Inputs larger than this on their longer side, in pixels, are traced at this size and the
    /// SVG is written at the original size. Trace time grows with the pixel count. 0 means no
    /// cap.
    ///
    /// An integer. Default: `2048`.
    public var maxDim: Int?

    /// Advisory wall-clock budget, in seconds; 0 means none. Gradient-band merging stops at 60%
    /// of it and the boundary solve gets 25%; the output is still a correct trace, with more
    /// fills or a less polished outline. A nonzero budget makes the output depend on machine
    /// speed and load, so it is no longer reproducible.
    ///
    /// A number >= 0. Default: `0.0`.
    public var timeBudget: Double?

    /// Transparent margin around the output, as a fraction of the larger side. The viewBox
    /// grows; the geometry does not move.
    ///
    /// A number >= 0. Default: `0.0`.
    public var margin: Double?

    /// Knock the background out: the face that covers the whole canvas is not painted, so the
    /// artwork sits on transparency.
    ///
    /// Default: `false`.
    public var noBackground: Bool?

    /// Black artwork only: every colour that is not the background is painted pure black, and
    /// the background, with every hole it shows through such as the counters of letters, is
    /// white -- or transparent with no_background, which gives black artwork on transparency
    /// with real holes. The edges are the colour trace's own, so a light colour on white
    /// (yellow) is kept and no pale fringe is left around the black. The background is the
    /// colour covering most of the image border, or transparency when the border is
    /// transparent; on white-on-black art the white is the artwork and comes back black. Off by
    /// default.
    ///
    /// Default: `false`.
    public var monochrome: Bool?

    /// No ids or groups, no trailing zeros. Same geometry, typically about a tenth smaller.
    ///
    /// Default: `false`.
    public var minify: Bool?

    /// Spend parameters on structure an artist can edit: joins between curves made G1-smooth,
    /// handles snapped to the axes and to 45 degrees, handles of one curve made equal in
    /// length, nodes that nearly share a coordinate made to share it, and rings that are their
    /// own mirror image locked into exact mirrors. Every change is guarded to the fit's own
    /// tolerance -- 3 sigma of the source point plus half a pixel, or 1.5 px for a mirror lock
    /// -- so the picture stays within a fraction of a pixel of the default trace; the price
    /// measured on 25 icons is about 0.04 dE00. Off by default.
    ///
    /// Default: `false`.
    public var editability: Bool?

    /// Trace transparency natively: each ink is a colour and an opacity, and the transparent
    /// ground is an ink of its own, instead of the image being composited onto a matte first.
    /// Holes stay holes, white artwork on a transparent ground traces, glows and shadows stay
    /// translucent, and a fade is one gradient of colour and opacity. An opaque input traces
    /// the same either way. On by default, as on the command line (where the environment
    /// variable INKVEC_NATIVE_ALPHA=0 turns the default off); false composites onto a matte
    /// first, as releases up to 0.1.3 did.
    ///
    /// Default: `true`.
    public var nativeAlpha: Bool?

    /// With native_alpha off, carry the input's transparency into the SVG: a face the source
    /// drew transparent becomes a hole, one drawn at a single opacity keeps it as fill-opacity,
    /// and white artwork on a transparent ground survives. Changes nothing for an opaque input,
    /// and nothing with native_alpha on (the default), which already carries the transparency
    /// out.
    ///
    /// Default: `false`.
    public var cutout: Bool?

    /// Scale the fit tolerances with the raster, so a large, simple drawing gets the parameter
    /// count of a small one. Trades fidelity for parsimony: small squares can come back as
    /// circles and thin rings broken.
    ///
    /// Default: `false`.
    public var contentUnits: Bool?

    /// Shape harmonization (on by default): marks that repeat across the drawing are redrawn
    /// from one consensus geometry per cluster, which saves parameters. A mark takes the
    /// consensus only where that stays within 0.1 px of the boundary traced for it and costs
    /// fewer parameters; a face another face is drawn against, and a fitted circle or rounded
    /// rectangle, is never moved. Set it to false to skip the pass.
    ///
    /// Default: `true`.
    public var harmonize: Bool?

    /// Shape-equivalence threshold for harmonization: the outline similarity (IoU after affine
    /// normalisation) above which two marks count as the same shape.
    ///
    /// A number >= 0 and <= 1. Default: `0.92`.
    public var harmonizeThreshold: Double?

    /// Which engine traces the image. "quality" (the default) is the full engine: the best
    /// fidelity and the fewest parameters, at about half a second for a 512 px logo. "fast" is
    /// a Potrace-class fit on the same palette, planar map and emitter, with a one-pass
    /// gradient check in place of gradient recovery: several times faster (tens of milliseconds
    /// at 512 px), a little less faithful, with somewhat more parameters. Options that only
    /// steer quality stages (precision, content_units, harmonize, harmonize_threshold,
    /// time_budget) are ignored in fast mode. "balanced" (opt-in) is fast plus four iterations
    /// of quality's boundary solve and a fit with tolerances a quarter finer: in between the
    /// two in fidelity and time, on rasters up to 1024 px on the longer side; a larger raster
    /// is traced exactly as in fast mode. It ignores the same options as fast.
    ///
    /// Default: `"quality"`.
    public var mode: String?

    /// Also trace three structural alternatives -- blend absorption off, a matte instead of
    /// native alpha, and a merge distance of 0.020 -- and keep the trace whose render explains
    /// the input in the fewest nats (its squared error at the input's resolution against the
    /// best one's, plus a price per parameter). Quality colour mode only; up to four traces,
    /// about 3.6 times the trace time at 512 px. Measured on the 246-icon screen set: 6 %
    /// closer to the artist's file at 128 px, 1 % at 512 px (9 % on the hardest tenth). Off by
    /// default.
    ///
    /// Default: `false`.
    public var hypotheses: Bool?

    /// Detect the faces of the colour trace that were drawn as strokes -- a centreline and one
    /// width, with round or butt caps and round or miter joins -- and write each as a stroked
    /// path (fill none, one stroke-width) where that describes the face's measured boundary in
    /// fewer numbers than its filled outline, at a fit as good within the measurement noise.
    /// Line icons come back at about the artist's own parameter count. Quality mode only; off
    /// by default.
    ///
    /// Default: `false`.
    public var detectStrokes: Bool?

    /// Colour groups: fills to draw as one, so the shapes between them join rather than being
    /// recoloured. Empty (the default) changes nothing. Groups are separated by ';' and members
    /// by ','; a member is a colour '#rrggbb' as it appears in a trace of the same image, or a
    /// gradient written as its stop colours joined by '>'. An optional '=' says what the group
    /// becomes: '=#rrggbb' a flat colour, '=@n' its n-th member (1-based; a gradient there is
    /// refitted over the whole group); without it, the member covering the most of the image.
    /// Example: '#c0392b,#e74c3c;#f00>#00f,#0a0=@1'. A group costs one extra trace.
    ///
    /// Default: `""`.
    public var mergeColors: String?

    /// Options with the given values; every option left out (nil) takes its default.
    public init(
        precision: Double? = nil,
        minArea: Double? = nil,
        colors: Int? = nil,
        merge: Double? = nil,
        maxDim: Int? = nil,
        timeBudget: Double? = nil,
        margin: Double? = nil,
        noBackground: Bool? = nil,
        monochrome: Bool? = nil,
        minify: Bool? = nil,
        editability: Bool? = nil,
        nativeAlpha: Bool? = nil,
        cutout: Bool? = nil,
        contentUnits: Bool? = nil,
        harmonize: Bool? = nil,
        harmonizeThreshold: Double? = nil,
        mode: String? = nil,
        hypotheses: Bool? = nil,
        detectStrokes: Bool? = nil,
        mergeColors: String? = nil
    ) {
        self.precision = precision
        self.minArea = minArea
        self.colors = colors
        self.merge = merge
        self.maxDim = maxDim
        self.timeBudget = timeBudget
        self.margin = margin
        self.noBackground = noBackground
        self.monochrome = monochrome
        self.minify = minify
        self.editability = editability
        self.nativeAlpha = nativeAlpha
        self.cutout = cutout
        self.contentUnits = contentUnits
        self.harmonize = harmonize
        self.harmonizeThreshold = harmonizeThreshold
        self.mode = mode
        self.hypotheses = hypotheses
        self.detectStrokes = detectStrokes
        self.mergeColors = mergeColors
    }

    enum CodingKeys: String, CodingKey {
        case precision
        case minArea = "min_area"
        case colors
        case merge
        case maxDim = "max_dim"
        case timeBudget = "time_budget"
        case margin
        case noBackground = "no_background"
        case monochrome
        case minify
        case editability
        case nativeAlpha = "native_alpha"
        case cutout
        case contentUnits = "content_units"
        case harmonize
        case harmonizeThreshold = "harmonize_threshold"
        case mode
        case hypotheses
        case detectStrokes = "detect_strokes"
        case mergeColors = "merge_colors"
    }
}
