// <auto-generated/>
// GENERATED by bindings/codegen/csharp.py from bindings/options.schema.json.
// Do not edit: change `inkvec::Options` in crates/inkvec, regenerate the schema
// (cargo test -p inkvec), then run `python bindings/codegen/generate.py`.

using System.Globalization;
using System.Text;

namespace LogoLabs.Inkvec
{
    /// <summary>
    /// Options for one Inkvec trace. Every property is optional and defaults to
    /// <see langword="null"/>, meaning "take the tracer's own default" (see
    /// <see cref="Inkvec.Defaults"/> for their values). Names and meanings are
    /// <c>inkvec::Options</c>'s, read from the same JSON Schema
    /// (<see cref="Inkvec.OptionsSchema"/>) that generated this class; the native library
    /// validates every value, so an unrecognised name is an
    /// <see cref="InvalidOptionsException"/> rather than a silent no-op.
    /// </summary>
    public sealed class InkvecOptions
    {
        /// <summary>
        /// Sets the description-length cost of a coordinate, in pixels: lambda = ln(extent /
        /// precision). Smaller values buy more detail with more coordinates. It does not set the digits
        /// written; coordinates are always written at 2 decimals.
        /// Range: &gt; 0.
        /// The tracer's default is 0.1; leave this null to use it.
        /// </summary>
        public double? Precision { get; set; }

        /// <summary>
        /// Discard features smaller than this area, in square pixels.
        /// Range: &gt; 0.
        /// The tracer's default is 2.0; leave this null to use it.
        /// </summary>
        public double? MinArea { get; set; }

        /// <summary>
        /// Maximum palette size.
        /// Range: &gt;= 1 and &lt;= 4096.
        /// The tracer's default is 64; leave this null to use it.
        /// </summary>
        public int? Colors { get; set; }

        /// <summary>
        /// OKLab distance below which two colours are treated as one ink.
        /// Range: &gt;= 0.
        /// The tracer's default is 0.035; leave this null to use it.
        /// </summary>
        public double? Merge { get; set; }

        /// <summary>
        /// Inputs larger than this on their longer side, in pixels, are traced at this size and the SVG
        /// is written at the original size. Trace time grows with the pixel count. 0 means no cap.
        /// The tracer's default is 2048; leave this null to use it.
        /// </summary>
        public int? MaxDim { get; set; }

        /// <summary>
        /// Advisory wall-clock budget, in seconds; 0 means none. Gradient-band merging stops at 60% of
        /// it and the boundary solve gets 25%; the output is still a correct trace, with more fills or
        /// a less polished outline. A nonzero budget makes the output depend on machine speed and load,
        /// so it is no longer reproducible.
        /// Range: &gt;= 0.
        /// The tracer's default is 0.0; leave this null to use it.
        /// </summary>
        public double? TimeBudget { get; set; }

        /// <summary>
        /// Transparent margin around the output, as a fraction of the larger side. The viewBox grows;
        /// the geometry does not move.
        /// Range: &gt;= 0.
        /// The tracer's default is 0.0; leave this null to use it.
        /// </summary>
        public double? Margin { get; set; }

        /// <summary>
        /// Knock the background out: the face that covers the whole canvas is not painted, so the
        /// artwork sits on transparency.
        /// The tracer's default is false; leave this null to use it.
        /// </summary>
        public bool? NoBackground { get; set; }

        /// <summary>
        /// No ids or groups, no trailing zeros. Same geometry, typically about a tenth smaller.
        /// The tracer's default is false; leave this null to use it.
        /// </summary>
        public bool? Minify { get; set; }

        /// <summary>
        /// Trace transparency natively: each ink is a colour and an opacity, and the transparent ground
        /// is an ink of its own, instead of the image being composited onto a matte first. Holes stay
        /// holes, white artwork on a transparent ground traces, glows and shadows stay translucent, and
        /// a fade is one gradient of colour and opacity. An opaque input traces the same either way. On
        /// by default, as on the command line (where the environment variable INKVEC_NATIVE_ALPHA=0
        /// turns the default off); false composites onto a matte first, as releases up to 0.1.3 did.
        /// The tracer's default is true; leave this null to use it.
        /// </summary>
        public bool? NativeAlpha { get; set; }

        /// <summary>
        /// With native_alpha off, carry the input's transparency into the SVG: a face the source drew
        /// transparent becomes a hole, one drawn at a single opacity keeps it as fill-opacity, and
        /// white artwork on a transparent ground survives. Changes nothing for an opaque input, and
        /// nothing with native_alpha on (the default), which already carries the transparency out.
        /// The tracer's default is false; leave this null to use it.
        /// </summary>
        public bool? Cutout { get; set; }

        /// <summary>
        /// Scale the fit tolerances with the raster, so a large, simple drawing gets the parameter
        /// count of a small one. Trades fidelity for parsimony: small squares can come back as circles
        /// and thin rings broken.
        /// The tracer's default is false; leave this null to use it.
        /// </summary>
        public bool? ContentUnits { get; set; }

        /// <summary>
        /// Shape harmonization (on by default): marks that repeat across the drawing are redrawn from
        /// one consensus geometry per cluster, which saves parameters. A mark takes the consensus only
        /// where that stays within 0.1 px of the boundary traced for it and costs fewer parameters; a
        /// face another face is drawn against, and a fitted circle or rounded rectangle, is never
        /// moved. Set it to false to skip the pass.
        /// The tracer's default is true; leave this null to use it.
        /// </summary>
        public bool? Harmonize { get; set; }

        /// <summary>
        /// Shape-equivalence threshold for harmonization: the outline similarity (IoU after affine
        /// normalisation) above which two marks count as the same shape.
        /// Range: &gt;= 0 and &lt;= 1.
        /// The tracer's default is 0.92; leave this null to use it.
        /// </summary>
        public double? HarmonizeThreshold { get; set; }

        /// <summary>
        /// Serialises the properties that have been set to the JSON object the native
        /// library reads. A property left <see langword="null"/> is left out, so the
        /// tracer applies its own default to it.
        /// </summary>
        public string ToJson()
        {
            var sb = new StringBuilder();
            sb.Append('{');
            var first = true;
            if (Precision.HasValue)
            {
                if (!first) sb.Append(',');
                first = false;
                sb.Append("\"precision\":").Append(Precision.Value.ToString("R", CultureInfo.InvariantCulture));
            }
            if (MinArea.HasValue)
            {
                if (!first) sb.Append(',');
                first = false;
                sb.Append("\"min_area\":").Append(MinArea.Value.ToString("R", CultureInfo.InvariantCulture));
            }
            if (Colors.HasValue)
            {
                if (!first) sb.Append(',');
                first = false;
                sb.Append("\"colors\":").Append(Colors.Value.ToString(CultureInfo.InvariantCulture));
            }
            if (Merge.HasValue)
            {
                if (!first) sb.Append(',');
                first = false;
                sb.Append("\"merge\":").Append(Merge.Value.ToString("R", CultureInfo.InvariantCulture));
            }
            if (MaxDim.HasValue)
            {
                if (!first) sb.Append(',');
                first = false;
                sb.Append("\"max_dim\":").Append(MaxDim.Value.ToString(CultureInfo.InvariantCulture));
            }
            if (TimeBudget.HasValue)
            {
                if (!first) sb.Append(',');
                first = false;
                sb.Append("\"time_budget\":").Append(TimeBudget.Value.ToString("R", CultureInfo.InvariantCulture));
            }
            if (Margin.HasValue)
            {
                if (!first) sb.Append(',');
                first = false;
                sb.Append("\"margin\":").Append(Margin.Value.ToString("R", CultureInfo.InvariantCulture));
            }
            if (NoBackground.HasValue)
            {
                if (!first) sb.Append(',');
                first = false;
                sb.Append("\"no_background\":").Append(NoBackground.Value ? "true" : "false");
            }
            if (Minify.HasValue)
            {
                if (!first) sb.Append(',');
                first = false;
                sb.Append("\"minify\":").Append(Minify.Value ? "true" : "false");
            }
            if (NativeAlpha.HasValue)
            {
                if (!first) sb.Append(',');
                first = false;
                sb.Append("\"native_alpha\":").Append(NativeAlpha.Value ? "true" : "false");
            }
            if (Cutout.HasValue)
            {
                if (!first) sb.Append(',');
                first = false;
                sb.Append("\"cutout\":").Append(Cutout.Value ? "true" : "false");
            }
            if (ContentUnits.HasValue)
            {
                if (!first) sb.Append(',');
                first = false;
                sb.Append("\"content_units\":").Append(ContentUnits.Value ? "true" : "false");
            }
            if (Harmonize.HasValue)
            {
                if (!first) sb.Append(',');
                first = false;
                sb.Append("\"harmonize\":").Append(Harmonize.Value ? "true" : "false");
            }
            if (HarmonizeThreshold.HasValue)
            {
                if (!first) sb.Append(',');
                first = false;
                sb.Append("\"harmonize_threshold\":").Append(HarmonizeThreshold.Value.ToString("R", CultureInfo.InvariantCulture));
            }
            sb.Append('}');
            return sb.ToString();
        }
    }
}
