//! inkvec in the browser.
//!
//! The same pipeline as the command line, compiled to WebAssembly: bytes of a PNG, JPEG,
//! WebP, GIF, BMP or TIFF in, an SVG string out. Call it from a Web Worker — a 768-px logo
//! is seconds of work and would freeze the page on the main thread.
//!
//! # Threads
//!
//! The pipeline is already parallel: thirty rayon call sites, and the segment fitter — 81%
//! of the single-threaded time — is one independent dynamic program per boundary. Rayon
//! simply runs that work on the calling thread when it cannot spawn, so plain WebAssembly
//! leaves all of it on one core.
//!
//! With the `threads` feature it spawns for real. `init_thread_pool` is generated by
//! `wasm-bindgen-rayon` and must be awaited before [`trace`]; the page must be
//! cross-origin isolated, because the pool is built on `SharedArrayBuffer`. Where that is
//! not true the single-threaded build is the fallback and behaves exactly as before —
//! same code, same `f64`, same output, on one core.

use wasm_bindgen::prelude::*;

#[cfg(feature = "threads")]
pub use wasm_bindgen_rayon::init_thread_pool;

/// How many workers the pool should start, from the browser's own estimate.
///
/// Returned rather than decided here: the pool is started from JavaScript, and only the
/// page knows whether it is allowed to (`crossOriginIsolated`) and how many cores the
/// visitor has agreed to give it.
#[wasm_bindgen]
pub fn threads_available() -> bool {
    cfg!(feature = "threads")
}

/// Trace image bytes to an SVG string.
///
/// `precision`, `min_area`, `colors`, `merge` are the tracer's quality knobs (pass the
/// defaults 0.1, 2, 64, 0.055 when unsure); `max_dim` and `time_budget` bound the work;
/// `no_background`, `minify`, `margin`, `content_units` shape the output.
#[wasm_bindgen]
#[allow(clippy::too_many_arguments)]
pub fn trace(
    bytes: &[u8],
    precision: f64,
    min_area: f64,
    colors: usize,
    merge: f32,
    max_dim: usize,
    time_budget: f64,
    no_background: bool,
    minify: bool,
    margin: f64,
    content_units: bool,
) -> Result<String, JsValue> {
    console_error_panic_hook::set_once();
    let img = inkvec_trace::decode_image(bytes).map_err(|e| JsValue::from_str(&e.to_string()))?;
    let args = inkvec_cli::Args {
        precision,
        min_area,
        max_colors: colors,
        merge_distance: merge,
        max_dim,
        time_budget,
        no_background,
        minify,
        margin,
        content_units,
        quiet: true,
        ..Default::default()
    };
    let args = inkvec_cli::resolve_lossy(&args, || Some(bytes.to_vec()));
    let t = inkvec_cli::trace_image(img, &args).map_err(|e| JsValue::from_str(&e.to_string()))?;
    Ok(inkvec_cli::post_process(&args, t.svg, t.width, t.height))
}

/// The tracer's version, for the page footer.
#[wasm_bindgen]
pub fn version() -> String {
    env!("CARGO_PKG_VERSION").to_string()
}
