//! inkvec in the browser.
//!
//! The same pipeline as the command line, compiled to WebAssembly: bytes of a PNG, JPEG,
//! WebP, GIF, BMP or TIFF in, an SVG string out. Call it from a Web Worker — a 768-px logo
//! is seconds of work and would freeze the page on the main thread.
//!
//! # Threads
//!
//! The pipeline is already parallel: thirty rayon call sites, and the segment fitter — 81%
//! of the single-threaded time — is one independent dynamic program per boundary. Rayon
//! simply runs that work on the calling thread when it cannot spawn, so plain WebAssembly
//! leaves all of it on one core.
//!
//! With the `threads` feature it spawns for real. `init_thread_pool` is generated by
//! `wasm-bindgen-rayon` and must be awaited before [`trace`]; the page must be
//! cross-origin isolated, because the pool is built on `SharedArrayBuffer`. Where that is
//! not true the single-threaded build is the fallback and behaves exactly as before —
//! same code, same `f64`, same output, on one core.
//!
//! # Two surfaces
//!
//! [`trace_json`], [`trace_rgba_json`], [`default_options_json`] and
//! [`options_schema_json`] are the library API of the `inkvec` crate with the options as
//! JSON: Rust parses them into `inkvec::Options`, applies the defaults and checks every
//! value, so the npm package (`packages/npm`) restates none of it and follows any change
//! to the options without an edit. Errors are JS `Error`s whose `code` is the facade's
//! error kind (`invalid_image`, `invalid_options`, `internal`).
//!
//! The positional [`trace`] is what the Space's `web/worker.js` calls, kept until the
//! page moves to [`trace_json`].

use wasm_bindgen::prelude::*;

#[cfg(feature = "threads")]
pub use wasm_bindgen_rayon::init_thread_pool;

/// Cap on the palette size a caller may request. `usize` wraps at the JS boundary (a 32-bit
/// `usize`: `2**32` comes back as 0 and `-1` as `usize::MAX`), and an absurd request here
/// would otherwise mean unbounded palette work.
const MAX_COLORS: usize = 4096;

/// Cap on `max_dim`, for the same boundary-wrap reason. `0` — "no cap" — passes through
/// unchanged; only values that wrapped to `usize::MAX` (a JS `-1`) are brought down.
const MAX_DIM: usize = 32_768;

/// Whether this is the threaded build, whose pool `initThreadPool` starts.
///
/// How many workers to start is left to JavaScript: only the page knows whether it is
/// allowed to (`crossOriginIsolated`) and how many cores the visitor has agreed to give it.
#[wasm_bindgen]
pub fn threads_available() -> bool {
    cfg!(feature = "threads")
}

/// Trace an encoded image (PNG, JPEG, WebP, GIF, BMP or TIFF) to an SVG string, with the
/// options as a JSON object -- `inkvec::trace` with `inkvec::Options::from_json(options)`.
/// Missing keys take their defaults; `""` and `"{}"` mean all defaults.
#[wasm_bindgen]
pub fn trace_json(bytes: &[u8], options: &str) -> Result<String, JsValue> {
    console_error_panic_hook::set_once();
    let opts = inkvec::Options::from_json(options).map_err(js_error)?;
    inkvec::trace(bytes, &opts).map(|t| t.svg).map_err(js_error)
}

/// Trace raw pixels -- straight RGBA8, row-major, exactly `width * height * 4` bytes, as in
/// `ImageData.data` -- to an SVG string. `inkvec::trace_rgba`; the options as for
/// [`trace_json`]. Byte-identical to [`trace_json`] on a PNG of the same pixels.
#[wasm_bindgen]
pub fn trace_rgba_json(
    pixels: &[u8],
    width: u32,
    height: u32,
    options: &str,
) -> Result<String, JsValue> {
    console_error_panic_hook::set_once();
    let opts = inkvec::Options::from_json(options).map_err(js_error)?;
    inkvec::trace_rgba(pixels, width, height, &opts)
        .map(|t| t.svg)
        .map_err(js_error)
}

/// Every option at its default, as a JSON object.
#[wasm_bindgen]
pub fn default_options_json() -> String {
    inkvec::Options::default().to_json()
}

/// The JSON Schema of the options: byte for byte `bindings/options.schema.json`.
#[wasm_bindgen]
pub fn options_schema_json() -> String {
    inkvec::options_schema_json().to_string()
}

/// The build target the contract fixtures key their SVG hashes by (`inkvec::build_target`):
/// `wasm32-unknown` for both builds.
#[wasm_bindgen]
pub fn build_target() -> String {
    inkvec::build_target().to_string()
}

/// Rewrite an SVG that already exists in fewer bytes: `inkvec_svgmin` at the JS boundary.
///
/// The counterpart to [`trace`]. That one decides geometry from pixels; this one decides it
/// from geometry that is already there, so a corner is a fact -- two consecutive segments
/// whose tangents disagree -- rather than something inferred.
///
/// `lossless` picks between the two rewrites:
///
/// * `false` is `inkvec_svgmin::minify`: every `<path d>` refitted as its cheapest
///   description within `tolerance_px`, stated at a viewing size of `judge` pixels because
///   "0.01 units" depends on an arbitrary viewBox. Buys the most bytes, and moves the
///   drawing by a bounded amount.
/// * `true` is `inkvec_svgmin::compact`: the same writer without the fitter. No segment is
///   removed, moved or re-chosen, and with a negative `decimals` no coordinate is rounded
///   either, so the picture that comes out is the picture that went in, pixel for pixel.
///   Only the spelling changes.
///
/// `decimals` is the precision written per coordinate; pass a negative number for
/// `Options::decimals: None`, which derives it from the tolerance. `document` also shortens
/// what is not path geometry -- colours, presentation attributes restating an inherited
/// value, comments, `<metadata>`, whitespace -- and removes nothing that renders or that a
/// screen reader speaks.
///
/// Returns `{ svg, report }`. `report` is `inkvec_svgmin::Report` with its fields in
/// camelCase, plus `bytesBefore` and `bytesAfter` so the caller need not measure the
/// strings itself -- and so the two agree on what a byte is, which `String::len` settles
/// and a JS `.length` (UTF-16 code units) would not.
#[wasm_bindgen]
pub fn svgmin(
    svg: &str,
    lossless: bool,
    tolerance_px: f64,
    judge: f64,
    corner_degrees: f64,
    decimals: i32,
    document: bool,
) -> Result<js_sys::Object, JsValue> {
    console_error_panic_hook::set_once();

    let opts = inkvec_svgmin::Options {
        tolerance_px,
        judge,
        corner_degrees,
        // Negative means "derive from the tolerance"; `try_from` turns exactly that set of
        // values into `None`.
        decimals: usize::try_from(decimals).ok(),
        document,
    };

    let (out, report) = if lossless {
        inkvec_svgmin::compact(svg, &opts)
    } else {
        inkvec_svgmin::minify(svg, &opts)
    }
    .map_err(|message| svgmin_error(&message))?;

    // Setting a plain data property on a fresh object cannot fail.
    fn num(o: &js_sys::Object, key: &str, value: f64) {
        let _ = js_sys::Reflect::set(o, &JsValue::from_str(key), &JsValue::from_f64(value));
    }

    let r = js_sys::Object::new();
    num(&r, "paths", report.paths as f64);
    num(&r, "rewritten", report.rewritten as f64);
    num(&r, "subpaths", report.subpaths as f64);
    num(&r, "segmentsBefore", report.segments_before as f64);
    num(&r, "segmentsAfter", report.segments_after as f64);
    num(&r, "paramsBefore", report.params_before);
    num(&r, "paramsAfter", report.params_after);
    num(&r, "guarded", report.guarded as f64);
    num(&r, "primitives", report.primitives as f64);
    num(&r, "toleranceUnits", report.tolerance_units);
    num(&r, "bytesBefore", svg.len() as f64);
    num(&r, "bytesAfter", out.len() as f64);

    let o = js_sys::Object::new();
    let _ = js_sys::Reflect::set(&o, &JsValue::from_str("svg"), &JsValue::from_str(&out));
    let _ = js_sys::Reflect::set(&o, &JsValue::from_str("report"), &r);
    Ok(o)
}

/// An `inkvec_svgmin` failure as a JS `Error`, shaped like [`js_error`]. The crate reports a
/// plain `String`, and everything it refuses is a property of the SVG it was handed.
fn svgmin_error(message: &str) -> JsValue {
    let err = js_sys::Error::new(message);
    let _ = js_sys::Reflect::set(
        &err,
        &JsValue::from_str("code"),
        &JsValue::from_str("invalid_svg"),
    );
    err.into()
}

/// A facade error as a JS `Error` carrying the error kind as `code`.
fn js_error(e: inkvec::Error) -> JsValue {
    let err = js_sys::Error::new(e.message());
    // Setting a plain data property on a fresh `Error` cannot fail.
    let _ = js_sys::Reflect::set(
        &err,
        &JsValue::from_str("code"),
        &JsValue::from_str(e.code()),
    );
    err.into()
}

/// Trace image bytes to an SVG string.
///
/// `precision`, `min_area`, `colors`, `merge` are the tracer's quality knobs (pass the
/// defaults 0.1, 2, 64, 0.035 when unsure; the merge default is
/// `inkvec_trace::color::DEFAULT_MERGE_DISTANCE`); `max_dim` and `time_budget` bound the
/// work; `no_background`, `minify`, `margin`, `content_units` shape the output. `max_dim = 0`
/// means no cap. `cutout` is `--cutout`: an input's transparency is carried into the SVG
/// (holes stay holes, a flat wash keeps its opacity); it changes nothing for an opaque
/// input.
#[wasm_bindgen]
#[allow(clippy::too_many_arguments)]
pub fn trace(
    bytes: &[u8],
    precision: f64,
    min_area: f64,
    colors: usize,
    merge: f32,
    max_dim: usize,
    time_budget: f64,
    no_background: bool,
    minify: bool,
    margin: f64,
    content_units: bool,
    cutout: bool,
) -> Result<String, JsValue> {
    console_error_panic_hook::set_once();
    let result = std::panic::catch_unwind(|| {
        prepare_inner(
            bytes,
            precision,
            min_area,
            colors,
            merge,
            max_dim,
            time_budget,
            no_background,
            minify,
            margin,
            content_units,
            cutout,
        )
        .and_then(Intake::into_svg)
    });
    match result {
        Ok(Ok(svg)) => Ok(svg),
        Ok(Err(e)) => Err(e),
        Err(payload) => Err(panic_message(&payload)),
    }
}

/// Decode, validate and prepare, run inside [`trace`]'s `catch_unwind` so that — where the
/// panic strategy permits it — a panic becomes a JS error instead of a poisoned instance.
///
/// The threaded build compiles with `panic = abort` (`tools/build_wasm.sh` passes
/// `-Z build-std=panic_abort,std`); there a panic aborts the instance before anything can
/// catch it, and no amount of wrapping here can change that. The single-threaded build
/// unwinds, so [`trace`] does surface its panics as exceptions.
#[allow(clippy::too_many_arguments)]
fn prepare_inner(
    bytes: &[u8],
    precision: f64,
    min_area: f64,
    colors: usize,
    merge: f32,
    max_dim: usize,
    time_budget: f64,
    no_background: bool,
    minify: bool,
    margin: f64,
    content_units: bool,
    cutout: bool,
) -> Result<Intake, JsValue> {
    // `usize` parameters wrap silently across the boundary; clamp them before the tracer
    // sees them so `colors = -1` does not become unbounded palette work and `max_dim = -1`
    // does not disable the cap.
    let colors = colors.clamp(1, MAX_COLORS);
    let max_dim = max_dim.min(MAX_DIM);

    // NaN or non-positive quality knobs used to emit a blank 99-byte document with no
    // error; refuse them explicitly instead.
    if !(precision.is_finite() && precision > 0.0) {
        return Err(JsValue::from_str("precision must be a finite number > 0"));
    }
    if !(min_area.is_finite() && min_area > 0.0) {
        return Err(JsValue::from_str("min_area must be a finite number > 0"));
    }
    if !(margin.is_finite() && margin >= 0.0) {
        return Err(JsValue::from_str("margin must be a finite number >= 0"));
    }

    let (img, (arr_w, arr_h)) = inkvec_trace::decode_image_capped(bytes, max_dim)
        .map_err(|e| JsValue::from_str(&e.to_string()))?;
    let args = inkvec_cli::Args {
        precision,
        min_area,
        max_colors: colors,
        merge_distance: merge,
        max_dim,
        time_budget,
        no_background,
        minify,
        margin,
        content_units,
        cutout,
        quiet: true,
        ..Default::default()
    };
    let args = inkvec_cli::resolve_lossy(&args, || Some(bytes.to_vec()));
    Ok(Intake {
        inner: inkvec_cli::intake(img, &args, Some((arr_w as usize, arr_h as usize))),
        denoised: false,
    })
}

/// A decoded raster, prepared for tracing and held across a denoiser round trip.
///
/// [`prepare`] makes one, [`Intake::trace`] finishes the job, and in between the denoiser
/// exports hand the tensor out to the page's ONNX Runtime Web session and take its answer
/// back. With no denoising in between, `prepare(...).trace()` is exactly what [`trace`] does
/// — the same call, because [`trace`] *is* that pair.
///
/// JavaScript owns it and must release it: `free()` after the last [`Intake::trace`], or
/// [`Intake::trace_once`] instead of that last trace, which consumes the intake and leaves
/// nothing to free. Not both -- `free()` on an intake `traceOnce` already took is a free of
/// a null pointer.
#[wasm_bindgen]
pub struct Intake {
    inner: inkvec_cli::Intake,
    denoised: bool,
}

#[wasm_bindgen]
impl Intake {
    /// The width the tracer will see, after `max_dim` and any intake normalisation. This is
    /// the size the denoiser runs at, which is the point of denoising here rather than
    /// before the decode: the network must see the raster the tracer sees.
    #[wasm_bindgen(getter)]
    pub fn width(&self) -> usize {
        self.inner.img.width
    }

    /// The height the tracer will see.
    #[wasm_bindgen(getter)]
    pub fn height(&self) -> usize {
        self.inner.img.height
    }

    /// The size of the tensor [`Intake::denoiser_input`] returns, as `[width, height]`: the
    /// raster's size rounded up to a multiple of 16, which is what the network's four 2x
    /// downsamplings require. The tensor itself is `1 x 3 x height x width`, planar.
    #[wasm_bindgen(getter)]
    pub fn denoiser_input_size(&self) -> Vec<usize> {
        let (w, h) = inkvec_restore::planar::padded(self.inner.img.width, self.inner.img.height);
        vec![w, h]
    }

    /// The tensor the denoiser network takes: composited onto white, planar, edge-padded.
    ///
    /// This is `inkvec_restore::network_input`, the same preparation the command line's
    /// in-process backends do, so the browser is not a second recipe — only a second
    /// runtime for the same `restorer.onnx`.
    pub fn denoiser_input(&self) -> Vec<f32> {
        inkvec_restore::network_input(&self.inner.img).data
    }

    /// Take the network's output — the same `1 x 3 x height x width` planar layout — as the
    /// raster to trace: cropped back to size, quantised to 256 levels, extremes snapped,
    /// alpha carried through, all of it `inkvec_restore::network_output`.
    ///
    /// The trace that follows is then forced onto soft intake, as `--restore` forces it: a
    /// denoised raster can look clean enough that the edge-width and ringing detectors no
    /// longer open soft intake by themselves, and the network was validated with it open.
    pub fn take_denoiser_output(&mut self, chw: &[f32]) -> Result<(), JsValue> {
        let img = inkvec_restore::network_output(chw, &self.inner.img)
            .map_err(|e| JsValue::from_str(&e))?;
        self.inner.img = img;
        self.denoised = true;
        Ok(())
    }

    /// How far this raster disagrees with `svg` where the trace claims a flat interior —
    /// `inkvec_restore::decide`'s signal, and the one `--restore auto` decides on. Above
    /// [`denoiser_threshold`] the input is treated as damaged. `undefined` when the SVG
    /// could not be rendered or has no flat interior to measure.
    pub fn residual(&self, svg: &str) -> Option<f64> {
        match inkvec_restore::decide(&self.inner.img, svg, inkvec_restore::Options::default()) {
            inkvec_restore::Decision::Restore { residual }
            | inkvec_restore::Decision::Keep { residual } => residual,
        }
    }

    /// The raster as RGBA8, for showing the page what the denoiser did.
    pub fn rgba8(&self) -> Vec<u8> {
        self.inner
            .img
            .data
            .iter()
            .map(|&v| (v.clamp(0.0, 1.0) * 255.0).round() as u8)
            .collect()
    }

    /// Trace it, without consuming: `auto` needs one trace before it can decide whether to
    /// denoise, and keeps that trace when the input turns out to be undamaged.
    ///
    /// The clone this takes is the raster only. It is the price of asking for the same trace
    /// twice, and it is small next to the trace.
    pub fn trace(&self) -> Result<String, JsValue> {
        Self {
            inner: self.inner.clone(),
            denoised: self.denoised,
        }
        .into_svg()
    }

    /// Trace it, consuming the intake. `trace` when the answer is only needed once.
    #[wasm_bindgen(js_name = traceOnce)]
    pub fn trace_once(self) -> Result<String, JsValue> {
        self.into_svg()
    }

    fn into_svg(self) -> Result<String, JsValue> {
        let Self {
            mut inner,
            denoised,
        } = self;
        if denoised {
            inner.args.lossy = inkvec_sr::Mode::On;
        }
        let args = inner.args.clone();
        let t = inkvec_cli::trace_prepared(inner).map_err(|e| JsValue::from_str(&e.to_string()))?;
        Ok(inkvec_cli::post_process(&args, t.svg, t.width, t.height))
    }
}

/// Decode an image and run the pipeline up to the point the denoiser would see it, for a
/// caller that wants to denoise it there. The arguments are [`trace`]'s.
///
/// `trace(bytes, ...)` is `prepare(bytes, ...).traceOnce()`; the page calls this one instead
/// when it has a denoiser to run in between.
#[wasm_bindgen]
#[allow(clippy::too_many_arguments)]
pub fn prepare(
    bytes: &[u8],
    precision: f64,
    min_area: f64,
    colors: usize,
    merge: f32,
    max_dim: usize,
    time_budget: f64,
    no_background: bool,
    minify: bool,
    margin: f64,
    content_units: bool,
    cutout: bool,
) -> Result<Intake, JsValue> {
    console_error_panic_hook::set_once();
    prepare_inner(
        bytes,
        precision,
        min_area,
        colors,
        merge,
        max_dim,
        time_budget,
        no_background,
        minify,
        margin,
        content_units,
        cutout,
    )
}

/// The interior residual above which `auto` denoises, `inkvec_restore::Options`' default.
#[wasm_bindgen]
pub fn denoiser_threshold() -> f64 {
    inkvec_restore::Options::default().residual_threshold
}

/// Where the denoiser weights come from: the same `restorer.onnx` the command line pulls,
/// from the same Hugging Face repository.
#[wasm_bindgen]
pub fn denoiser_model_url() -> String {
    inkvec_restore::HF_DENOISER_URL.to_string()
}

/// The SHA-256 the weights must hash to, so a page can refuse a truncated or tampered
/// download the way `inkvec_restore::pull_onnx_weights` refuses one.
#[wasm_bindgen]
pub fn denoiser_model_sha256() -> String {
    inkvec_restore::WEIGHTS_SHA256.to_string()
}

/// A panic payload turned into a JS error message.
fn panic_message(payload: &(dyn std::any::Any + Send)) -> JsValue {
    let msg = if let Some(s) = payload.downcast_ref::<&str>() {
        (*s).to_string()
    } else if let Some(s) = payload.downcast_ref::<String>() {
        s.clone()
    } else {
        "a panic occurred inside the tracer".to_string()
    };
    JsValue::from_str(&format!("inkvec panic: {msg}"))
}

/// The tracer's version, for the page footer.
#[wasm_bindgen]
pub fn version() -> String {
    env!("CARGO_PKG_VERSION").to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn contract_input(name: &str) -> Vec<u8> {
        let p = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../bindings/contract")
            .join(name);
        std::fs::read(&p).unwrap_or_else(|e| panic!("{}: {e}", p.display()))
    }

    /// The Space's positional export, given every knob it takes at the facade's default,
    /// writes what the facade writes -- the JSON exports and the page cannot drift apart.
    #[test]
    fn the_positional_trace_is_the_facade_at_its_defaults() {
        let d = inkvec::Options::default();
        for name in ["tiny.png", "white_on_clear.png"] {
            let png = contract_input(name);
            let positional = prepare_inner(
                &png,
                d.precision,
                d.min_area,
                d.colors as usize,
                d.merge as f32,
                d.max_dim as usize,
                d.time_budget,
                d.no_background,
                d.minify,
                d.margin,
                d.content_units,
                d.cutout,
            )
            .and_then(Intake::into_svg)
            .unwrap_or_else(|_| panic!("{name}: the positional trace failed"));
            assert_eq!(positional, inkvec::trace(&png, &d).unwrap().svg, "{name}");
        }
    }

    /// The tensor the page hands to ONNX Runtime Web and the raster it gets back have to
    /// agree about shape and about the crop, or the denoised trace is silently of a shifted
    /// image. An identity network pins both, and pins that a second pass over an already
    /// denoised raster changes nothing — the quantise and the snap are idempotent, so a page
    /// that denoises twice cannot drift.
    #[test]
    fn the_denoiser_tensor_round_trips_through_the_intake() {
        let d = inkvec::Options::default();
        let png = contract_input("tiny.png");
        let mut intake = prepare_inner(
            &png,
            d.precision,
            d.min_area,
            d.colors as usize,
            d.merge as f32,
            d.max_dim as usize,
            d.time_budget,
            d.no_background,
            d.minify,
            d.margin,
            d.content_units,
            d.cutout,
        )
        .expect("prepare");

        let (w, h) = (intake.width(), intake.height());
        let size = intake.denoiser_input_size();
        assert_eq!(size, vec![w.div_ceil(16) * 16, h.div_ceil(16) * 16]);

        let tensor = intake.denoiser_input();
        assert_eq!(tensor.len(), 3 * size[0] * size[1]);

        intake.take_denoiser_output(&tensor).expect("first pass");
        assert_eq!((intake.width(), intake.height()), (w, h));
        let once = intake.rgba8();
        assert_eq!(once.len(), w * h * 4);

        let again = intake.denoiser_input();
        intake.take_denoiser_output(&again).expect("second pass");
        assert_eq!(intake.rgba8(), once, "the round trip is not idempotent");

        // And it still traces, through the soft intake a denoised raster is traced with.
        let svg = intake.trace().expect("trace");
        assert!(
            svg.starts_with("<svg") || svg.starts_with("<?xml"),
            "{svg:.40}"
        );
    }

    /// The page verifies its download against the same hash the command line does.
    #[test]
    fn the_denoiser_constants_are_the_restorers_own() {
        assert_eq!(denoiser_model_url(), inkvec_restore::HF_DENOISER_URL);
        assert_eq!(denoiser_model_sha256().len(), 64);
        assert_eq!(denoiser_threshold(), inkvec_sr::detect::DEGRADED_RESIDUAL);
    }

    #[test]
    fn the_json_surface_reads_the_facade() {
        assert_eq!(default_options_json(), inkvec::Options::default().to_json());
        assert_eq!(options_schema_json(), inkvec::options_schema_json());
        assert_eq!(build_target(), inkvec::build_target());
    }
}
